apiVersion: apps/v1
kind: Deployment
metadata:
  name: seerr
  namespace: apps
  labels:
    app.kubernetes.io/name: seerr
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: seerr
  template:
    metadata:
      labels:
        app: seerr
        app.kubernetes.io/name: seerr
    spec:
      nodeSelector:
        node.hardware.gpu: intel-igpu
      tolerations:
        - key: node.hardware.gpu
          operator: Equal
          value: intel-igpu
          effect: NoSchedule
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
      containers:
        - name: seerr
          image: ghcr.io/seerr-team/seerr:v3.1.1
          ports:
            - containerPort: 5055
          env:
            - name: TZ
              value: Europe/Moscow
            - name: LOG_LEVEL
              value: info
            - name: PORT
              value: "5055"
          volumeMounts:
            - name: config
              mountPath: /app/config
            - name: cache
              mountPath: /app/config/cache
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            seccompProfile:
              type: RuntimeDefault
          readinessProbe:
            tcpSocket:
              port: 5055
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 5055
            initialDelaySeconds: 30
            periodSeconds: 30
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "1"
              memory: "768Mi"

      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: seerr-config-pvc
        - name: cache
          persistentVolumeClaim:
            claimName: seerr-cache-pvc
            