apiVersion: v1
kind: PersistentVolume
metadata:
  name: parapar-pg-replica-pv
spec:
  storageClassName: zvol-local
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/zvols/postgres/parapar-dr
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
---
# CNPG names the first instance PVC <cluster>-1
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: parapar-pg-replica-1
  namespace: parapar-dr
spec:
  storageClassName: zvol-local
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
  volumeName: parapar-pg-replica-pv
