apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-pgvecto-pv
spec:
  storageClassName: zvol-local
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/zvols/pgvecto
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-pgvecto-pvc
  namespace: apps
spec:
  storageClassName: zvol-local
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
  volumeName: immich-pgvecto-pv
