---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gitlab-runner-k8s-secrets
  namespace: gitlab-runner
spec:
  encryptedData:
    runner-registration-token: AgAb06KwcIm4066UPV3qe7IvuMzMAjdCI4wxxbep7mtNm6bn3ftzLsiJ5mEzl+G82+sDMPNMvLD0WSeDCkr6REdgCnk4eKCC0Xdv5jk8oNS0ym0jaWAAreJy4+Z0IO5AmLLHHFry/5R+IZMOVaoDZjgizhrHVWh4/b4TwYKqsC08IS/4xpIrogjRVnb0qb4TdYQK9HQtuejPt5UPWX/bnt3M03cU+/Q6ZZOgAgqyHCEbATxAFUtBqgkJL3uKPHo6Ld1uZk6TzDnnRR5VSzZA9Ajx7gEG7XHRM1r2Rn8fajA7S1W7Ep42Sk9hH/FPuHfrnntZDtWMASfbvElj4QipOdxUxy++4R6sGZVzpJejJi2gOfJLPQApeUebe8uc7zoKzvTQDGlUDOcuKn4yKsPEC5feBrdJe2udH6U/JdlLIi00zN9bnEJgKhCF3xF7h78ZDgLEXBon6jUPXQlA6tGMAFsCectyfs2XFv/j1QAO+eP08Bq/TS3syVkAYsgrfnPqGA0xzImZoevIkpe2HKPvhBLMHyFZZmvkUNH03spnOLVsOeW2w6/DnadxsvxwVgGtPKjtuVOM5/O2KoaM4+CJUr6UbxFZ5gigwb+bB++hNO03ObGc5nBafW8uz9c9B0+As1K61lIPSAf7TQZ2CYqETAkRSybNWxFOMOPuUvCfF9ya75JV2pvtxgGj8FuiPJso+pY=
    runner-token: AgAbRXmNmTceERzQov6v8HAtNCb4L8wvcesPjKcH0EFeRw/97Bjr1WyZxXEgkwnxhOc9DiH2vcKlkcBFFNZUFHORRyiJXqVie6bcuZw2C31S+h7gnF8fto8DJHtEq/H0BwOH97IfhDvaTW40pZ8xhsMkpJGLuFm93/uDFsQg9NsZemM96fUCUEi5x2ntXLJ1CuYlTKCRHu3wQO4Jqi2qEegcBeWpa7VSWbqyaUoQzZxL35jCfzEQd5DM+3WSPM64/hLqOW6yjdiO+whmpcPHI88dIyq0oXEerjqu1TAZu7BUDa7OnOszaPmkW+jeUwINfc9DKfgYOYrICEggxtjPpNel7NPeie45RNWvegH+QabPH8ziLzKmOD3uxeort/oCf92mM8GUBgFYLprvor+k0TMZHAfhGIkIhoVKwvPsOB2XypfYezh8DjlkVaLaWzYfNEU21xYhMZd5H0RHbViEiT0fA1uSvC0sv6hlnhXIEnfqfKn5NAG+qjcrPAAE6ObYOy9w57LBOYC2u3DRzJ6UlgxzVloQ9+3ULJRYjPYW3SKcHvte8/+JUL4/MA86gugM7LjTLZy0TiY1FSgp6u3AhQD1zPPFXxIc2exNsCPfgs5I5wv6fqg5AC5RMZBQrK3qENiZ0llMLiKr/+NZ4TMsJuE3xKbScUDnbd/LJR/e28yv8RdgO9D0DPIeWHaJcOVVg7W65E3qzMt6Y0gHkA242G4VVS5ST6nypBEsYUcftBUpNwqx500NJ1YQ80xW7nHoHFKLYTzxl6OBcA==
  template:
    metadata:
      name: gitlab-runner-k8s-secrets
      namespace: gitlab-runner
    type: Opaque
