apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gitlab-runner-k8s-secrets
  namespace: gitlab-runner
spec:
  encryptedData:
    runner-token: AgASE2patbcMpBeW0LVbmvhM3Yf3NG0FT9IOwg6yMtlGWCq9lqL98ddJxxT4a6Y4oSu6EynIOcJp6XahQ1kvIdzJ+mrxUrtoSUwO5BQfRprJv+L34hw5Bla53Key3uj1L/l4ufBWrOVSRizcMipAgGs+rBdk7Qds8pwAVLCkcf/o9YCuKDttMTC/RWIwpGAFTPHieOeHOFGWatUbw0fKBWlmS8JRhxxuliyU+cCGZQp4JpV3bFCwo4F4qg3zkzCaq8MMXD4KPLQGH92IR7t0PZ2AeoCRsnKwf7F03YZX6cq2kPZ/RnOxf1NCm0VOfVSMdjs1Y2b4tk/M9cU5RBBtUGLNlVrht6tGDnw+iRfWwqNGZySxZVpj2viXzOCpim5ekpDMbgqOdmq7C3Haj7jYDmT8Grku/BhogVAaflRWApQQBO5DHLtCNSBVkQrViSEIDlvorpNeJIRSNg3pKAhU1HHfIzUKtEQa1Cs9ne9p1oDqRDWF5Ch4wGcfX4BJX/5lwSsBOo12ISLEuK0AZ48oKJd49dSN3+QpG+b7zO8JzPSCEOjbENlIK0EmPBBz2043M/O4Uc3ihTySAfjtN9hQzJ0p1EsBh9p+yQj7We9sgFN6it6ZuoI01ok2webtz357cmiLvQ0jMSEBi7w1x9Ukwl1ahgS0UN3aSt1bBd5jKBbNDdhcfawddZkUgKSa9ZbpKlYhWs6pOR2HUzaXIZ9+VJWVYQsTIrUjrIuLlcahr/uPbckb5N0Sc6k43IR2i2My7MqIbrI4574hKg==
  template:
    metadata:
      name: gitlab-runner-k8s-secrets
      namespace: gitlab-runner
    type: Opaque
