---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: memos-secrets
  namespace: apps
spec:
  encryptedData:
    MEMOS_DSN: AgCdEdR+c6GhGA3ZQDjbZSxzQv9ET6NOa6MUt7ZRFFwpnOyOLiHsJz7ARwieljSAXfI+vrVzPZQ40oYSfyPQ48kWqFkiLbfRo/4hXAZXM8ek49IZHgoMqkPPemj/zDlF5ppweYakwi4K1wOtLFgk9bSxuJITYtlbs4hh46zk4U7QzN8uT1lD7Z5qOX5Mf1loI8dFGdPIUIA7sXHWfiT4U8hp4ymu0nWwNC1C5pQaWB4qD3gMR+QD4eBvNZX0KDflkOImhjvrzap5TMhRdwGBLT+GDvCbnkm0WKYGaepAwxiXGFylzffyi2rHJOJsIrb8s8sZYFVUkesAufvP81gtTUxJIsdfySoA3aRswNvjqi7OV6ev33DgNtDwRm/QkB6Am5g1ri9bGgJWe2x2pRuUs2I9mg8wf7YSJ0N8TKOFC9N7jzk/vEOi8gt3MRuJ2yj6J2c7D0WlAYvnL/sopn4ZP4b/bmxa6ly8s+lK+nVYFhKUbmb/I/2N9GUzr/m+6IHcRxlIeCdVeMz5PVQUcXHr+8lbOnnCMW9Og0OJQPTPkeieZRfcLNJN5P9C8JqLFdcqXhJM6rQeJT67uebBI5wdegIb0fY8rHVoU5CO+U4pMRPYkqvIP0qFRjXz2Hs4qFCiQoYsWv2mrviBjnP2K0MsCol29N077LbiZNkzOwAK8FEXi2nvi5O7vAYcVmh1/8UX+TLrK93MUslvQwBSUTtj2OOqjoP4/V18C8riZbsuVDMJHgYRx7lb94LK9dYg3slIXjBYSKwIGQtGWIAO0Qsx1CZ/MDRkaNRXATDFG6GOiwvvfjh36stE8CyMJtMYhq0r
  template:
    metadata:
      name: memos-secrets
      namespace: apps
    type: Opaque
