---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: databasus-minio-secrets
  namespace: apps
spec:
  encryptedData:
    access-key: AgC4EmlkUXUzH3Zd4sGaJwGVw96lDP5DDgX+ghWoaohiWOpOu1nGLclXiwtCeaYhaXVDF8fngfy/IVkQ2Lfv1gTwMiCgV2/ojguUEYWw7cru2vo2bfmgy3i2WX/418oVgewl5SkdnWZYw5oxW/jrAymcZ6dirD9FN2y8qywC7Irz77XCSlGT8M14+Jmr4U6XlgDURdrRmS8h9qVFz8ruBnuKycKQ0NWMAaSjtZfYyL5kUEaTBUZARbD4qZyPz818JyI+XLUo+9GHu+H6G6np9DbVPCugVrROAGDbbIElw7HkXCarL6hVuBExe2bc5pZl2oU9Hzoamp0gWKKRLn0+6JzxGqdOgcbBPFpSvS5brLRtpMowkRE9krfibFlgDOBJ7aKZE7g7AHQNza/PAXBA0iWpSNC46HeVwKcZ3r0OenBJePuDG4v6bKFwhSFEi73ny6mhaCEny1pSw93lLBI1x07cRSfdNmoUoDRlJcqc0y+MO8zXgdmpi9ttx3rrkJAmqAFFEljOWgB8AE25NMV/OcNm+/ra1BNrEPs+mMOmiWSVw+jEhHznodhi+fpZMqgonolaJzYhqS1l6wjVnUqQAGgINTQgAXk7g+XOoznAJIO1nFBd3+SVxOWtwuvO2KAUDfM47WBEwZLN1kzraEfQZNSQqAIH9HjQbTw5WMQM8YQad6PCxk+ZihV5MFXnq44lDEp6rlfVzH3exKz5CFrjFw==
    secret-key: AgCEjAS8/3zX5B+ArMfMcs1Wu0C7Wu+XglWYmvq6d3tO8rq79c7jJp3sw3GHkOG+mTWTZIFSB+fBhSUxZWhCr4j79+YNC/IbzPCW5LupIs0s8Du0eoN1FcL9XHxBlETAtNLLGn6n4ZEf3nuZmGzfZl0fbV/UndJr3M7kG/ZCOSw+XHybPETUlNBxUiBrOmWuitUB8o80tQxMPGJEN/p31m0smNmBjJRcqYx8ZnmZbUFJcvVq3AQtESmCs6ocNxqSpLr++Pkf8dCFaQ7cSBamLUIOvbrInlTpneFdgiNz7MqLsvGPLzgiZD70HwIoUnOSU5IlIlUrtnwSW2Kd6em0sxyUJ0eETevw5y443fRh8vNxB+LtiCIlKkiR4UEkJnkUwGk0JZyAvqeYDRLFgYcZOabfS3ZIie0N1lNiOg/9YA9Hqdjk0m6Pkgwo/mOzIRYqIlwS0EeR83/tmR2piEeCl30xX5cmDqIALMxbGD6blfSdXuOZmKfr8lZCGo9MZfsCCpEtZs3ghRFmBu56a2JEZrv4NiFzsd51/El6hcS0ZWU8+dZqz/RbRTLyJ60dJiHQwAHvIxuQ/il1Rx6OnmN8OXe1yOmzKa3mdNA5bYw4baMfJaeDE+r1fZ3xzHG5idx07g9QJqBNRt9I62wFCEOjV5JHtGrm7T1EnNdOTK8oFcGP1bR6lwcOm34pDVgAYuuNsssXd+VXwyQaHk1KJP+SNmS7YSsxNqL+SQnBr3YTcgmFcg==
  template:
    metadata:
      name: databasus-minio-secrets
      namespace: apps
    type: Opaque
