---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: code-server-secrets
  namespace: apps
spec:
  encryptedData:
    PASSWORD: AgB3mS4cMZhDozFg4xyuRDaffB4sC9Spo1HA9LAc29kuqNqNc+qeysIX+PrdEkFIsJLgE8phWw53k36opuoEYcTNjmnxqfyGHinV9tvtBdl98uHy/MV+5/g3GkoLFK8MdHHRHRBRW5uKawQdxO8Ng4XS5Ve4OxBZlA2qSjIyd7UKKT6xgr8NAipZoKcJnf/TCgFgJUSlSGz2RjlZ9Hz1zR4E+J+CPj92A+QBMS0iq7ZhFCesxPLKcqd5pa8nuYP3nxJg4UjIoL0n6SS7F/bgCtGN9LFmOg4Hd4p+9OrOhXET9EWu27JFXRV2j2od+qrX+qYSQ8JxFmzuXehyL2GbBfEfKvgVoD7v0vVpUeRkM6xO3MMQHlsZbfRBw4hsnWVAzvUVV8uc2dIz80L8ntk/+F+PSqMgbqJM65H2gDN8M/OpBxH3rmCgIrngWqUIYzP8d6GfA56GuqT6wbpAqgr7uqne8hOLz+dwXrv7/zxZn8wZ3StAi+EW0SpfvLbM5gxbmyxV+XccDt9/tOHg8nXH/8Twt4aCzKo0i7VlQlgSFT4p4mfXBDSo4vo4WaSV+R+IKWyq0mUDZKpjWPwsL0XUxVhpVogBOl2EJSoVZj8LI/kP0uBTZ9474tP339oOqeGqzGCOU1a90IkwklPAAc5hpzRYsUdgg5kaRd9HY0EuRH/ggoOHGW4VcK/BqZdHgP6h6089LXxrWFH4YA==
  template:
    metadata:
      name: code-server-secrets
      namespace: apps
    type: Opaque
