---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: vikunja-auth-secrets
  namespace: apps
spec:
  encryptedData:
    config.yml: AgCpLHBojGBcpiQOWXwZK9cFVEL02aUA8xB0Lh6DZRQQZTpIOAS5G1H0E13gg6qjazb0cGiia4EQ/K4yFn6LM0ycohK3ViTXx+R4jg0DqY9pFhh49kUYYFU3bstCe69rFxCUCzylYUZbObZcpYl2ic9PVdZ0j1bYWxHfUnULpa99o9PoGydaQibplBiQpVK+ehAIKJn8dcv1Z8APMrxEu4at6QYcJxkHDQFOss7j3Hf8fYr3rHL8eGsbZKkK3GncAXmFT1ISUcrLbQJK3wxaXHg+AkgEG0oPsBlT+2LQxq9cjM1g5ArgjyTf2nrRwRkAyiBRctUWJkH8wslLMMfdeKaBvHGr7GJ6ERUG1BVT1RzEcSDBQvvoe5ct4fFPUKWttyKA+23/h8Wsu+1BhZbRx6vdr+KK89pYIDVmChSB/b3CltDeriZVcnODwm9JtDchtdrjPr7UgNEdoHcBl1FJQuVqe75HV1jvBsVTahOYI9Ovw6WLICvdOiMGHVkOOFPdIO3cdbEs3L7K8hWCFB32VDuYmtpkzcKKdKjqgLgcHL0vxu+7lvsgCOKGrWcPQxlQeZ3GCRKKSp/2i3Dyf8OloROXfs/NrNuj/UJN55goLw719fmhiVkGQvrXihqILTTS1V8Aj05iHdahFgZ4Txi+UcurBQBnNxi3FJrek4KJmxu0+oNMRpIFY7oIX6g3h23yq1xdXrSdEQyUZxUYjpkQU8IumkvuTQdoj7WKnkz5XHWkT30E7Au+epAraUy4ZvQiAK2wO+acIZXIsCRi93ghh2wqGHO9HexwteY5arW57e1bMZm4jcSqZssZ9OnYmxJyNINd3tCg66hWH4faWwRXpgnIcdD3/OVSW1QRb8ZqzVBd2O0PUbnR1BX3HP0e8c68ms8c64alxuFdkLO01HynmLPw8Vra056c3y2Ief2le6kWFFJVX2J9LlwujwT3SEE9CQwl6Jkk10ujju7BcTzDJmOFuAIdSmqpZXeF1pG+0CBPlfoVp3+00qx7vRJQ3Yk9hASB4xc3Z5GQ44W1Z6HV30AWFt/s7Sk9ZPKd8ia9KF2iN36CV0qS8MW7ZjwPEVLnKv4HCjrXohd/OZ5VCkMMx2NTvCd/U8j2nwVuUeNg9wbFAbFozgwmhCU5eDCJ1x/T2ejCJoalQ+a7U4740qCNs5G/9J+uexclMhem6W4xnqLB1AaLgNTzTse07u88gvrUf//lxhyrCTRwrtygwHtx9KJpOOI4dSVw03gmrd9irrC9thvhA3e/dlggpndacLGimA8Ynao=
  template:
    metadata:
      name: vikunja-auth-secrets
      namespace: apps
