apiVersion: v1
kind: PersistentVolume
metadata:
  name: databasus-data-pv
spec:
  storageClassName: nfs-fast-manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /mnt/Fast/k3s-data/databasus/data
    server: 10.0.0.4
  mountOptions:
    - nfsvers=4.1
    - hard
    - rsize=65536
    - wsize=65536
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: databasus-data-pvc
  namespace: apps
  labels:
    backup-level: important
    backup-user: root
spec:
  storageClassName: nfs-fast-manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: databasus-data-pv
