---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: frigate-notify-secrets
  namespace: apps
spec:
  encryptedData:
    telegram-chatid: AgB9YKnTlIjK3qaPx/pLLraQ4ShI7N6+8saxIcDRfWr18X+Cc8KLjagojpzTYITLfxPxZs/E73Ir4lxJqVLdTTb0+ViPSf4KhM9XJr9R6hiV30dvfRciT1EdLFPGhIAs/hST3Yjdhrr3Y0iCSq2V5LzxJnKNQvh/BNya7vNjBF2pfFuuumP9kNN8Qhp35ijOCmt/sWVQI+y5AgWe6IwQH0r/Sd79cNc/9S4AW1S3ka021E+OypZ3j9R7RwJOgmT+6aTCSj5RaqHlmVB/AbPJgEvj0hpXsvF5KtVosywPI+fxmjB/qVQ0cBH5kYG4XmtjSY8k18W5iprIshP9nNcFScP/f2B5vQIrv0dZCYX1m251k2C7v94W6hg8xRwqy3/8p6dD1j33J418oDjJMeuOur3T9QAr8zPJ/ibLrqwDF5ZSqlHfY2klgCWAD0CGlafPt+ZPeLv9UBydASBCBjXE/0kvhgpM2BtmmE3O7fW7xiSaVsThbxoNb+kwAvcea6Cq2hCjrAV04ixK6QpmAFIAh2PK3z8SXhDYKDOXF9bfLxm8+PGgadQM0/LoMc9CnrdKMhQVTiOQACgk5B9mqSZyfmMxk+JzjZSBSQGDD7TVpD6pgfixfnG/AmgAcv4U2h6S4KS7f1TbMiVYuUPheb+vWExvLwjSR2jwiTB55ZfeFNCx/XZlAeElv+1LxKjqkj5UzP0A0r2L5YgPHhur1FNpAQ==
    telegram-token: AgAfxJHrJVUMGuTEZRiEUq5TYnaw6KJv+/CEvSQNoNdtoT/eAEa8+5FiXZ3YvWckK2pm9a33T9Ip6aLDtKO8OddqwoCCrqEX3xjTPJzibDOOtTAGxU+Ulb86AjVxRL1MiP/wLlhVt+LmRzaOl1POhd6HGsgE9KU7QiX7KUR3YUIFwoI5ZKGDmY2saOe0m6T/85fFiNEMEBTbT3L/Cpr2aiOdnwjqTnIsCW+BAZKsQCmLL6nZEklisvRhrn+KjhgODH9mLRt5SKo+teWUaHlvLKMVjr7rm6hIjfpWU9kNKgi41HnV7OoEQdVRo53WCh2Yt810Hu8938p7D/0oNzsF/mLlXffQq4raPQ3hEoszqqdZtYq3dZmrTjy1Y7FoYVDLicgAgZwVMd5pWYOBSYsyzAlhksYTMPjJFJCDrvGWVc7s2a8/end5PjvOIMO/tQ15nlaShkVAq8CEQYPl6YBftehLlRYpFN2JQaEkOuB0a83TUmoYXNpFZilsznWe7Wmiocs/qfSWp2cY2vc3lBNVE8fMPxTWzTJPMtTg92cIQVru/e00gATXc4Zl4efsFeO5duAoi/dPZSsWyr3Cxv5cpDGkTrWkxa5UXSNk4YodB/NCEC+BwqP2Gp9kFS1vNKofUdPCUI1vZ42CD5iIuut3MGIvhzEnJvvigDrN+TxLl9VDIOo1Dq9cK9lbmbZmnTsXDuiPZdT5l+fpSLTB0xK8/V9DK1aXD3kj6qBZas11C+MYrOOyWpOTG5Xg44yYvxY6
  template:
    metadata:
      name: frigate-notify-secrets
      namespace: apps
