apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pvc-archiver-n8n
  namespace: apps
spec:
  interval: 10m
  chart:
    spec:
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      chart: charts/pvc-archiver
  values:
    name: n8n
    archiveName: n8n
    sourcePVC: n8n-config-pvc
    destPVC: backups-pvc
    schedule: "35 5 * * *"
    exclude: "**/cache/**;**/.cache/**"
    securityContext:
      fsGroup: 1000
      supplementalGroups: [1000]
