resources:
  - crowdsec
  - storageclasses
  - traefik-middleware
  - xray
  - xray-edge
  - proxy
  - reloader
  - intel-device-plugin
  - minio
  - reflector
  - home-root-ca.yaml

  - traefik
  - metallb
  - k8up
  - error-pages
  - traefik-args.yaml
  - traefik-metrics-service.yaml
  # nodes управляется отдельным Kustomization с prune: false
  # - nodes
