apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: uptime-kuma-secrets
  namespace: apps
spec:
  encryptedData:
    db-password: AgC6XCWAUWZ5K12G3pwbBjWDOvU9qmHwemUvTkUMK6zcUmI89VQ9H5NfgWpJSGZ5usoBQb2fGxH7+bG6i0ACuPRBscLrwmR9V8j7QNb9PxCmpwAVM2bacnYp6Cw8GPHaenjMrV9z1zY8fNZbUwwTqnwSAKraj8hs8O+5dnAQPKH4aY8QFBW7K5EvcssRyfjeNTSPamRaX9HpxbwVKnYP9Ghn4oXxKJKYm6Hqh8A2otITRCNzE8LD6U013+g1Z1QXKoSXD/w3ZFrutA/tcThCGqx0tL4yQ5TSrBAy9drBkrpwekOfYeEybomo5DsJQOjYg+VvvsgJWLl0wbZxwK0VjGEnNMxpzUGTR8Vjw1jr/WE1K+MIf0ZpPTRwcYq5GpiDLFkyFwFylkGXSm7o5O1oxvVX4yapSj+g7nwD/EBAtWmVH/PIbhUxHGqpyvM9gxQ3nAEkwYw1Gjh4KRDNgeJX5x8nIR9GHHNKYii9098KxhJK8YQYw/9OFnMJJ2HyxySUaIXy0ALy65njw46zcRTdlVOAWfewvqa/vR2WNrZybb72Zozs6sFq7jyoN6OEBpBWlW1gn32nfMGIzMiyJrTdWlwnYi0TBz+0I2+1doV5dkND28yp5nnULVAM+3DxmF4ZcQnktnS1YASWHSJE7LLeyn7oq5EJnGSQaQDJTbkXBn7UvL3w2b5wBfDbChgsEEv0O/UJjdz05Xi7lUKORzL2RLh4BTvItpcjp9bdNTmestfaKQ==
    db-username: AgAcANu2Em9Q/2DLKr9G6UvdZzoZ4zDFz1N5iB+SxXA2Tmkga4dBJD2d59HK2KuSezF1lpWioM34ylFfNRXZytAZ1ZoWEOkhYiZSxX9G/Y/Ots3E7LCUl/VKUYT2n9rCm5eB3ExXNaQx2B2wNfxGbKBG0uTV2S9w6RwbJ1MYb5HT/d68Wk3xPcGoGHzMI2O7Xx/a5PLH4hsu64BAitvRHVwRAHzfo/NZT1angW42ST1SCOjmhjqk32EK/LJMIzcvfHUheAD2wgjeDDxbOPVYR5ZL6kfI09UUTo3vTzzki7NvLQldjYqT7Iijj2HVzlZSop9K7jQcxZG/YHxVfjltLy8QMCieOvpDTDYrGo7DKw4JNZsRLxJJp1lQ3FLcoTw1wAa2dkSIPYyhxDeP24bQO8iugguHWDNtsYOtgxEc1/mJ0atPcniRG0z8cr2H+nLF8cvIJbvfdGrG2ONoj3km9znYgvGsSnOeo0otNp1dk2y90rTYJoCdsFDplrZDGJjHNvPq9cNVAPOpI1JZTEeJeSk0aVB6YFlaKfF0MtSQw2ec8NilvIxc8GDrMq4x+//Qrdgi6BlFxnQEs7fJ7BmIyMllWoJjqbK61LXYi6T03UvpvnS4mBt9mcWpJvx770G//Jy8azqAsxTfaw/avlO5H/7JhS3UEHP+iijKobesiILCGfR1pXEg51tWZWNbgKLqpq3hQxVw9GAhQwNKyw==
  template:
    metadata:
      name: uptime-kuma-secrets
      namespace: apps
    type: Opaque
