namespace: monitoring

configMapGenerator:
  - name: speedtest-script
    files:
      - speedtest.py

resources:
  - deployment-prod.yaml
  - service-prod.yaml
  - podmonitor-prod.yaml
  - cronjob-yolki.yaml
