apiVersion: v1
kind: Service
metadata:
  name: speedtest-exporter-prod
  namespace: monitoring
  labels:
    app: speedtest-exporter-prod
spec:
  selector:
    app: speedtest-exporter-prod
  ports:
    - name: metrics
      port: 8080
      targetPort: 8080
