apiVersion: v1
kind: Pod
metadata:
  name: mysql-recovery
  namespace: apps
spec:
  restartPolicy: Never
  containers:
    - name: mysql-recovery
      image: mysql:8.4.7
      command: ["/bin/bash", "-c", "sleep 3600"]
      volumeMounts:
        - name: data
          mountPath: /var/lib/mysql
      securityContext:
        runAsUser: 999
        runAsGroup: 999
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: mysql-data-pvc










