apiVersion: v1
kind: Pod
metadata:
  name: postgres-recovery
  namespace: apps
spec:
  restartPolicy: Never
  securityContext:
    fsGroup: 999
  containers:
    - name: postgres-recovery
      image: postgres:17.7
      command: ["/bin/bash", "-c", "sleep 3600"]
      volumeMounts:
        - name: data
          mountPath: /var/lib/postgresql/data
      securityContext:
        runAsUser: 999
        runAsGroup: 999
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: postgres-data-pvc










