apiVersion: v1
kind: PersistentVolume
metadata:
  name: code-server-data-pv
  labels:
    managed-by: flux
    app.kubernetes.io/part-of: home-cluster
    environment: production
spec:
  storageClassName: nfs-nvme-manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /mnt/Fast/k3s-data/code-server/home
    server: 10.0.0.4
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: code-server-data-pvc
  namespace: apps
  annotations:
    k8up.io/backup: "true"
  labels:
    managed-by: flux
    app.kubernetes.io/part-of: home-cluster
    environment: production
    backup-level: important
    backup-offsite: "true"
spec:
  storageClassName: nfs-nvme-manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: code-server-data-pv
