---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: acmedns-credentials
  namespace: cert-manager
spec:
  encryptedData:
    acmedns.json: AgAS2RXToaiHDMDlET9PDLzpkB3afaS6wCw25pqdznlGACnxr8aOTw/mh+zo6ghuwHNbn+swk8pYQ5SKTPAZEOplA+2mXkftkydx6MB7nOCLqtybSpf4ndOsCJQahQJq9XCuhEz0u0N6zzzbPW38xRDx8R1ZdQhPqJS0yqJhGMipFO6Uv8yCGiCYe19PtIeXnSj3eKY6ul7ZYNgqjSGSthwMkDYNSJgnps9roWIiAZExqQfBnGqw5UMFlWzkyrZ4C2EWEuxIZZZSTbuOEv4rSrbhj9zc/Cow/58GQ8fJMmJAQUfv/OmwVG2CsYkWVyozYw+wEnIMg68UREAxPiKKL9xKAk0llnwIKNcJILt9Dg7pWN3F7gfSdTlaqYGM1p4A4/xQu9NdISdKaFpXWNWPTkQ2SYFjTYf9akHxxETLYpzp2tCT2YZH7Dwt4pLNdSZPDBhtsIkZ0CKGSsyx0nZdle1qOPrd+KlzTuIcmMl+wkQuQPXlNMJj5cw8XhPHgFBqqf9chUag4PnNNHA/3Hfhx1YVihD1IYXtJlbfuqZsv2y58ce9Pk6pDsE6mWSwNyRoR9AEq0uq5lkPaDJb9e/Ru+sIeJO2X6eAx8ISRbRsyquUOVh/oW/2mNuLIiglcidlyabfljEgr2p+n/EvcDrxJqAX/Flq/ir+KBBQZeNm7IB1lsDoZS0y1rrCjvey9VEo/ni87P7+U9yfJKmE60TuKALFDUIAAoqPDnm8IUyeFFWJMbfXz3KXcZ/uCc3Hs+wSsNGSNobKYesRUH0eMXu/HYi/k1pDikKwCxdZ623MxM7SX8V3pkx27HZoMkHU2R/kz2KNOeZL56e0uByjJ8A3upPMUfzwapgM6HKeSQ+8TvSfTDzcC4xwZFeydbhoh/cePmGmaEXMfI1S8BquMMfSzMUmP/bTndczOe+S+OrU0Mlij7eTAf+eIK2abCINEWLxmYiF3Oghh0gFXro4eKY3Nua0wy7P6AvsQze5jk9pDatq0V3cGlBRzXizbsjAgcxX6RnvCX9vF9ECLWGtVY+9LqZ/C4B+eWEAxLm+I4dFCFLDpfKbtmMlpoquPk7URJ1dSxSn+Rso+ouBsvqOJWj+zIVQZ8D/qA0TBiwPqTXRX7hWGTsxSHXz4bGzPc6L4uqHrOQoOfBgUT6caP5YbgkxFulBeL6I9XzUjtfUhkqZiPVCYm6CcQFJwHaYbB3X9TRlvRG0lhpK+uvqFmHXQiFetaFVjHiXqRiWJFTkMJ6k5Bl1reQVtc7LnLBYp9woXAhFc8IOevCQeSXtSBOCFsqCibG4rdIS2EthEUxJI0HdRr28idtxM+5kckJ1qIumqW25rZVWGhbbAJY7UH76vxf3IRsHAvTjxUYU+zh5q/FM24+X0uts0ccO3YUst+J2umCzO4EPoAJuuUhxgvZtbhwk8iEcI7ViW3Gh64LL+zt+eEp0pMCPGLGeqpgWvD/67Hez26tphR/wMk0AOSl64G0=
  template:
    metadata:
      name: acmedns-credentials
      namespace: cert-manager
    type: Opaque
