---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: acmedns-credentials
  namespace: cert-manager
spec:
  encryptedData:
    acmedns.json: AgAnrJ3diOtvNMlIDch1PHAtD8HbGMYWyK7FvLOpgtd9qhVZGzEMVonh2xV5D03VQPNwaCW44fewAlZ08LhzBeXMobSwQxbzh44GMwnXv+CdapLMU+gwAZTBV2MAgVOMKNtPGrIiDkNz/3GQR3ZT3vuTFY6/3wm6UFM0SoVllKFpfuFlMtxTnceuKWJVia9YwOfzntRlBgbSyEP4erO4dDCj/RE/DRJ5qY+ppo9lnvY0gbS7RHAAjpBkl/9/Sda2YqX4FDJxVmafMRdsgFyb320ENBh23VsV1m0fkhaFavBaBp6QfpDOKo/eCijimx0eH5dYq9lBTd8aq8UjRDopYs0v0Z7TdkpFaublEL4aTxoDxP/3kky1GmqbP+KbBtZKf1mkV/y3DtLa/9bIrvEwzAYZ9xFw4SMgUCNXQuXraWJJBfTb2pMvRYcMrLlZO3f0DqwGmd4b5sQ/PfY9lBsVRwafL5+AbGpqzQyMWxyfQ63NgT0FeKxo2APl0KcTCR/lcKR/iWLUA6Gu/smmLQPgXeD5LUyQyquTNMJ/u683UXq6oSZdZR1TF1JHbyu0o1dTEO7AvE3PNvOCBRG/TMsanGAlqyH0LAy/65xI2Z/VxqY1ydHx4h01EtQ/HBXurydyhPuWG1ebcyxDMCKuLEmgLSr/WqM5wdaul7glVUdQPSg13FB2UrnTLOQIxe1nXJ45QyAB1dFfq8uDUAEUA3d9KzlzueWAAEGGO2AwloVK5zZ5ZSQttin0JxkyU5U7JDe8u/4CqI9GT220yHk+cna/EcIXTFkNaz9blkw7mPNGjNu5nDx56SpzawqQDeDGUoDTNch2xo+mJcaz/7f+kfLzixUl8z24t6mimDTz2IzLEx9LqQ7Ah+c8gSn0fPKrQuI/49lxLft985toaTDwh2nQZ2Jz32eTp0aIf9NcBL/iYJ4L9MGH4zeC25mO+lfv98SOiG+5w5ctid0FywDg/rG9o5zXkoQcqe9NjLWdllvZGlq9IjK0TrEqmNTyK3gZAGfJPRRZk9ysZeuZ2v/ri/tLlsevZJm8aPH4n6U80JlraomjU5//llaWQi3fMABIaqgmpoBcFzA5xvw=
  template:
    metadata:
      name: acmedns-credentials
      namespace: cert-manager
    type: Opaque
