---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: acmedns-credentials
  namespace: cert-manager
spec:
  encryptedData:
    acmedns.json: AgCY/3PcMDPdNod8tGOqUqtND/DQ4xexevSWSb7xwSwbqlS9RbDgmZwB00QbAOaWceeHMdqqCiJQ3nFKmUZ6mFQobJfEtyPshvjDYZxuWDkNAiN5v0esU8XuQJrEC6LplC1WScfPsqgr9tCSKa8BgVL4SAtL49xvq+Lg159jXXBP+coX0BcGnxruhU3gShlf1c0KoN/dDGd589zZmd6jwkgGlzZwdmdxbWOgmOxn9Ilp13iOxdbdLREiwTJOmUv2JqwDxlCAzLQ59mTyi2hos7xvM+mQGHH87Pzzl73antoycYe3R2ksynutAb4uVY9VW2OrsigBODPWV5NQGBbrXwWdp7uMgsoU8mOl4078Km82h3uXhUFbM+CPXzqQYyl9jt4ajiUNBivH7F/i+SQIGHk4AJYjckFUqSKZujPmTCVH3xyjgQ00yAktIGW3Y1TJg8Bxe4D9SIfezNs0hEyKlJc/MPSenF5ACMUflsWOTzajIeyY5cl9ZkafJHLVisUR72DJPpPL3Rn139nwrSFmRCYBCG1XqXGRnrbP4E9xemibuPT1NEEnV77vEgNcLGNgRLw3FVIgYLoYe8vKzssyY9/FOVJKzF+lx72YgG7aQkGJpnJhRbFCK+JJkJAjrvRkLeXfhcEq4q+FqyZnD5z+G4aSWMBRnq+zgSWQ7osR5ggvpAtu6WQgBaqJyGM1XX58p8MEqnPfy2UkgFit+M9H6R3i77XwvUyVm7Vh7E6zzboTEtfoyI+vroIpQkca6vI8Xt+ytYWfJtQ5kYrekchcTwZBVFJQQPKRDLNR/KYi8H+28HZK/83+Dzslwrwwft6vghk5KI7ZI1DMF92ULMCmHN5eNaeM7wvI6QXk7lZG/IbwktcPGSQh4txfcg5YCZD3tULIP4b5MUTFAnOV0d1AZS0SFf3uU2hYx/X/s+KNWwa1dWlFYQhJPbLY4lZ53T8SnZdm/BQH756adfjAWk/iXpb7miANXQ5pthCdFO3Tg7kOZuJDptN7pdxtdnBECAj8MEsAWtzpUo+2lC+kEGt6MYjBzViNZDRk
  template:
    metadata:
      name: acmedns-credentials
      namespace: cert-manager
    type: Opaque
