---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gatus-secrets
  namespace: monitoring
spec:
  encryptedData:
    TELEGRAM_CHAT_ID: AgDG2tDqpBRboDJz5ZzibQB9Ty3dd1ulfO1QuW4kKN/FsN9J9fqKcsynKx0tvN5/FemxAzcUBdzfw1FexxliDLT2+ZpsWskkKOSpu7b96Lqo6L7ondc36DSpoZmhy4qFJ+Z/tWPqq/EB7qJZdNmrzEEDj7Gdojyau2W67z3auu8tUYF6o5uNKRp5WVCvh9tqgZxzEosGOrdtTeWaTnoUPF5huXA33tlH3FeumzUpAE++qt0Ii9wCBmhTwhC+c7t4jdFDo8ayqmzHLqRMx/saZtzuPEegSy7jqMZRH1jxxLON5v1YB8p9q/qumgP4a1QmVDKXdNOJ7yOlUSETEfExbf7izqvF5BrK+5sHHRHbf/NwMkWMY377yYp7NEG9SJ4Tj+FNFC9DP1e1rAu5JHfyztfPzk7zZ7NMJjF4EoIKNaqCIpWlNjIc6gY/FtDTjJrPBCqEgSoDTaFmbNGBikD7LryV7Sc7b2YKffDToOjIo6yjrKX/nwdavkt81abvdNehrYDlOg/bwhhjXrpqAxVfKXpAvjQdHJe32do6qOpVGtE2XDNLtCvhrd/cQ3Z8vHVORXCU9gfFhA8NiQ/EHUecpwhLDUn4EQYxnsxi40k8KX2FUv2Al1T4+zIEj+ji0+9pJ2CbNgdPr5WXIZ9BW3TCMgvcZESs/VgvEYUrYz0bJYe9SXeSrvd4ApQeFX1QDmefTF9kyrpyXzfZKw==
    TELEGRAM_TOKEN: AgAPDqb1cvt/uWSFeX4GIWs3oicJW1Boh6AZNCtqWyU1AdyEJENBMwQZOXCt7Pu0uJCyT5FPVgPPmrHwn2Nz65lOQFD6o8QNh6O144A9XQtM9BFjU0bzFT4KxZJyUlCgjIEvxV/PMk3irl4kLsNDYnbeVEnJ5Bx0gUM9fGxz6Zh0RDY+7cvvT38i5eMqenP9heY/GRInxmFHq1ouC/c2quvZ3LOMTzysxR0yO87otQwbHg4xhhOMHbAdh6lzZQkm6xe9tILHXz3IuH0J++3YiZODcCVds0tSMs/oeOpwrUfwTJicQvRBY42WBuOlyGP2zzwuOvqFK9OaOpAF3Aw3SpYe2sMkqwqNTEwJJZMYdLs3LGFbfehHq1sxatARaKa6oFI9fzi0WwiZ+5oZH5TzpYVGePte2cF85dunJTWaaRREPuovp1AaXHeNO/U8gJ3j0YnUjhV0GzzQLkhPnFc6dkW3EY+Y+m7MQvLZI9A5CbmlqWFWD1ihkx4Ls5Yntc6rblpmXmi8kPlJL7iiMotIl9+DEcQBmeWwgALkxaLmqoBK7m9w2F5m6L+HlR99Xqg9y6v4GTFMMRyWQlgXN0B37UstZGWAOP1PnycCNyvR+328DGBuxIlyOCp+eaGVYmDG9pOvmo2nFdAe65i7jFZZExpRHJeozXlQyGn3DqZ4H3HDmHxh/mIEYIUyb9oyH0CP5mQZ/uoGnGbFohbPm412N3OenHf7ehRsk9kj4P1y5ubiBENTIzX0bk/Kl633I4W5
  template:
    metadata:
      name: gatus-secrets
      namespace: monitoring
    type: Opaque
