---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mailtest-credentials
  namespace: monitoring
spec:
  encryptedData:
    MAIL_PASSWORD: AgCWDqrcGqzOumaWAONKSQLPmwftCO8B3H0CaZ0Vs7XKDRMhZJhEpAbezjQYPHfXKu3ZTqZ572IhXRHSeYdwSERrpDBJmLyXFyVV7TKqGYZMOhdPwJMMlFubGQjQVrlHcfKF+n/Hp4w2nPeO4ex9HYDyc3+XGQUS4YEFSYXfgcxLCxyHkzKUw01yhKewiAiv0cTnnXYFybfktcTjtxkWppHm5l9VKb3TTFG6dtIRjlQzrLfK6XolLn6CgZvsVBiWqoCepU0xiqH3A+fbPA8vprFk5fb0e7tv/nuUh2K101lYRWSnQOPcP2n366rIpBaV2DMgxo7O15m2r0U7h2/NioPnpNkmLVYzZqOyJB3Np6xNoC1gg1bl+/76nlle9iy4CpWlrv2inYtEgPqqg6D2HOtI73W6hDzxPE4mBR61rnZMZWCb96qHLvKglArFokV7IpWA53967E+TCnNfC+Emg4easnBCgioaYBSvilIStptU4JiYa7951dXBoZnjrvSgxSgC7gvLc4Wt2PfMhpp2LtMn0MXs1adAhra7vnRVAE9qPYapPeZgMgogoto10d0M9ndrKQ1vIu7xxMrXD0/vr+RRNtaN1BEmQEXYytslxK4V5eZK3klzogBsHc2YUy8xC0izULkoQw1XUM57KwWd23vopcKqGagBiajTseh9aDa3LGHehBYT1X0Lt8dNHHgFdYI0eBg5PNhLr9VPX6+HE+LPgtQNO/VrDWELI4hzM7W6ag==
    MAIL_USER: AgCalt8xC0byupgNloiCk82ww7kwjWddQ/0M+CI8mc3vHoyMdV67Maz66weCV5GpWd/MbP51qroSkkr465pGClJwnYsmUnFcCjvH5Cn/Rb2AFyaXUHVFnbvMSSn8rPEl/EPKEwooWS6d6gZ1eYjB4DIfL//GO4CVAv/2j4mOQd4wlr/NRCf3T8kmxr4c05v6c6LpYEQOTO/+1wMIRKNzPJup9V4JcEDJjnQ9LpxJXgPsbPwS3xlz5x49+tKDfwaAx8diK2A9wFX2zsx7PaNOnDJvFE7ygFIJYFwtarDigsdt4qcm32jEsEzRzTwAPIgTSg4dzwD4K9rLhKwxHepk3PXwp3ahHZd27I1l5Pop2hmyMT+RS905Yudi20GlBnnbcTIBKAUNNK3GrJMRinsd+XaLB8jR+rog7pfemXJtKjjNqHd4ymWprSV1bmgWe7I84qAkHDfHKuTakWkmCflgnmyBNyzkCNKIB6ifDbtEGgMFiht56ExQFXxnzavXbfzsIwVB8IDmrzZDd2ojC0mt35WJ1RNIBvAFjreUPej9u9z26n46NrA2QrNfSREwptQQtR0vBDW10qCl0gPuxoN0GFnWSEc+i2N0qoV6UQGcHBtdNWZUur6RgrQG4v1+LXXBl5lC1eruLH5WwwF9M06Ebay7rehDgEsgpl7q3g0Fc/VleiPCyqnElqFEMFeoDYMdKmFPgLqtlCiofqym9o+PKp+BRiGZ
  template:
    metadata:
      name: mailtest-credentials
      namespace: monitoring
