---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: uptime-kuma-secrets
  namespace: monitoring
spec:
  encryptedData:
    db-password: AgA6PNGEF2TotVOJ5HN8cagtr6Z6mYtKUn+E9PJ6ytn8h1Buy03cuBf9poUOLs/TZrNS4M8DHkNRDnjgd/sdHvx7gyCpPYCXdVpoEvOfa7fBImofqnd+azv5vhU3KOR1DM4l5YSEmP6HrRhS74wRVBOrVI4i/viIHucgBLkwpcb/MG+DWyolrra1h3hPBm1cEpRwY/b3y1GO4aFsklxhTwmZSm09u4sKO3oRE4Z1X/4ZNg7OM97monIP01ilrdjND5P/1tWzuGurtsZfRfkgMdLMgUluwxlWmcZGqh/zb9rWxFwNsF1DF+5CjZOpBQcSf9/bsuLDNmXfZjzuSy3lpLyN8SFzS0XRZ8pvS61vccp+Nnn59oThwJUIZ4DRRpUi4gwj+JC5VZA2Z6mYcva9zRkiK2n6prbRXYTDZqDc2kuAYDnYE7bQKj+NMNSrch3ZwqBEH7r9NP3uzhcaEZELGh8J3cysWwZjopJ/e9YbY8x+k2t/rGWK3yrZJ6zoPNXOLis25ry11pIVjp3U0+ZC7/U145+mHS+zfSrsbkoUmwHkB2dczckwto18hZzUjnJ7XUBC0iHLsdv8KC+tsJ2USvRPlsgzQQXksjDuz7hweFtk1cdD20SVz7iVLIOW+hTyPJjWq0z/8vxvhWzRf2zYARaKQobmzDIJmIAJv8ydwVYBFGL5VgS/HI+yxFt6UNnm/9Mq/hpLEv+t/AHMwcXe/C2OnHyEoLezVKbfPKkIaTXIiw==
    db-username: AgCTcSIVziT/j+6zGMR797whwNH/RSsWOYbwvMY5CPMReLxWWSqVN10ZYZGGPIQnSHlvlKTLmbUcbjlfol+zGrnUoXHd1+flw+KSxXiXCgj4tydkAfINi0o7F9rpW/OfVT+fMoFXsCj9em0QLmx8dFBdRZXLCjSDI9jr0lsSZXzR0rXpu0CNMbVKJJSHKHD+av5Oiz09PYcTCo+bRwtO9eq6abYd5/35pVEu2UIfcApd1m4haiKtQBaKpXdpzoLyhzIlKsJhLuNyQ93AWzV6ZR+fa1rbWbHTU/hj1SmvoV7M5l8oX7zWE4M/iUXxj/BJRkIdUpLadKQmndgsITXWggUXo6G926iOfzOT2Tozyr0lgGH+2zc+NYV7C4RAZkH5TwMhrQ6JsiNUuTbAoAjO6xqEE7kujNe+eglTskYguk+FLeT6NrwMyJqU1pQIwbXdeqHtzwudATHb8ynGKb6Cjur9Fl8nBISCjsK3wZkVnwU8OtLDedNdbw1FWAulWQMhEIyOlQD+F/e29fMyvuygmCxUb6PlHFlnTIGfNl3J/rEd/q1n5KWAzaerBQQLUT9AKUf03iwufM6vbiKL1J8VRR9lIvb9aSEwlRMjAPEdelYg3cS4SGc51bbX1hkfExqKUjLQvpPj9MNXr5fDNOG7vuP5ysInqrHm3woE6fAseSVNfyKAUTVxBOcffOqOxX8ZE1+LhXHglzobBuvjAg==
  template:
    metadata:
      name: uptime-kuma-secrets
      namespace: monitoring
    type: Opaque
