---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: airtrail-secrets
  namespace: apps
spec:
  encryptedData:
    DB_URL: AgC6YIjfBUcL56Zd9SDTaM8U62wWUV+1l3fMmwEbarh5NDISfEcM1WQrsVYKfb7WvlBUQ7ohQP/EYxFJeQ+p6dxR/laRXCxHgkEgpQLXQVCDZvhnRE7Zm/ubzTU1Sw/w+GRpb766TVWUM1VWbhAshjDjYCeBiBri6HzFkGIBOx6DA97Z1Xt4rSqbf5yvvyOsvxH6oYq8UvJoCm9iD+n0CynyO3E8HNwrwl/AgextVYSxykX3MOTaIMgTI4tleoDWOIaIso3rY7pAKLMetFA7eZCyGq5gTtnVy+r6MvLcjvyaCFat7k5gkccJ4FUdrBeD7mxY4ntyWe11LYE1+xX7CUQNwffTTI9OQ73UedrtbAtPjQRHUEekpWl3MPhiSYkbzsXAV/0OssB2X05wafuH6+nfC4bz6vqSBAkV11xcHgA8pTy+uayy34ENXdGtY6XBCYh7VzgmP0WquafNE4OQGEWWjaPGvj4CxP/SngezlfLO6RqzBSlcg93bqbrV6cJgNaPhpJPvtGYwZm3jJYPTA1nx3lKken0b3vdKVXBQe6x41Wc3KvCipvbn2XbHw3X2jIUHO8SPSFlqLO8S5rrzsVISg9CvC9A9Ul87i4uKURPMPpwnJ/fh0sz5QRbfrcc7Aezr/WOnjhsU+eiaJKXlcJo056X0Z/CpHQFV/+oLUueH2hrlv+yGKQojdiH4boWtwYCwJB+xcJ1McWo07eysS+pSU3c7Kie9gZZ7eV5LvV9NmYNX0iLoGB2JOFLN5QYe/d613Tnld3nqGWQr6yaDwxlGu63ddC0Ok1TDx/n32xJBhQaC2NMLVDNSpERN77V/kfEgjDHIa+qpIAwvj9tU2UY=
  template:
    metadata:
      name: airtrail-secrets
      namespace: apps
    type: Opaque
