---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: airtrail-secrets
  namespace: apps
spec:
  encryptedData:
    DB_URL: AgBCCILPsds3fwIR0YTRvzcKbT1fDpqri+tf4pO01VgSEel1cP3ndENT5q059JW4u+RhVJ2nbjQ5QiDm6K5R7Inbn2ESgy0UVjL2hP/ODaTNluI+er/LR0QKA7N9a3KssCLE+FXDFWnzfgkmEBrnrYUhf7fNHr8iizJPt0vijpQ0RCg3Rk5RMwH6Gfhct18N0K4QRgg1abziD7WH9/vNLdhw0UDPSLhUBN92H2sENPtdEwteS5vPSCYKsHX0OPAedHZPebl5d5oG+3s78jLQ0L8O1fNSQbgy5WEcO4x9mOSoMHr6W5oAUTeQGuhWFLMrsrdkMkGjT2Pq3bS1ppFltpE8K+tVkTAfC797a+5paklLR8u08jQeH4oq61PMAZr3+h6MlvQ0xW+iqezmYbedM2vTiraXRX9dWzvKYlrSUiOXJinPp7pD99f1qlB/U+OaQFlRDfjv3vPdONkLeckiZC5CMSlL1Z3ijr4/ok7egzhNPtl3ZCaMvrAgNPz+J6P9IwgJ8QyXn+ZDX53rqkBw/SIzwxxbl0PA+mZIwTXsrJcQ3aqeIPtCv7ioY31YM1JdViwmolaJnb95H6FRiSzJS0i4QBleMmj2I/dHAN3/HObh4sbbqf3kHs7Y+xBvjoDFv8cR72H1h+1/AQ/z2jy/hv8KmYOZ/vzX7moMSjEkF8eGvtuCAebkpde2PntgqMPwA1y6ifInPfH0644FC86xkmGSZAttlhTWO7bQqvjJFsGHJAqaQ2TqSCrYQroVAEz7RsLGHlr4zNSbZ1tPCIfuwI7aZoCAFiWInEgDUG5vbB5XUu8xA24oqXCs7TW5txa7WPyS+A==
  template:
    metadata:
      name: airtrail-secrets
      namespace: apps
    type: Opaque
