apiVersion: v1
kind: ServiceAccount
metadata:
  name: lab-staging-ci
  namespace: lab-staging
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: lab-staging-ci-admin
  namespace: lab-staging
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
  - kind: ServiceAccount
    name: lab-staging-ci
    namespace: lab-staging
