apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: speedtest-tracker
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  jobName: "speedtest-tracker"
  metricsPath: /prometheus
  scrapeInterval: 1h
  staticConfigs:
    - targets:
        - speedtest-tracker.apps.svc.cluster.local:80
