apiVersion: v1
kind: PersistentVolume
metadata:
  name: uptime-kuma-data-pv
spec:
  storageClassName: nfs-fast-manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /mnt/Fast/k3s-data/uptime-kuma/data
    server: 10.0.0.4
  mountOptions:
    - nfsvers=4.1
    - hard
    - rsize=65536
    - wsize=65536
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uptime-kuma-data-pvc
  namespace: apps
spec:
  storageClassName: nfs-fast-manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: uptime-kuma-data-pv
