apiVersion: apps/v1
kind: Deployment
metadata:
  name: mosquitto
  namespace: apps
  labels:
    app.kubernetes.io/name: mosquitto
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mosquitto
  template:
    metadata:
      labels:
        app: mosquitto
        app.kubernetes.io/name: mosquitto
    spec:
      nodeSelector:
        node.role: edge
        node.workload.class: cctv
      tolerations:
        - key: node.location.type
          operator: Equal
          value: remote
          effect: NoSchedule
        - key: node.role
          operator: Equal
          value: edge
          effect: NoSchedule
        - key: node.workload.class
          operator: Equal
          value: cctv
          effect: NoSchedule
        - key: node.reliability
          operator: Equal
          value: low
          effect: NoSchedule
        - key: node.hardware.arch
          operator: Equal
          value: "arm64"
          effect: NoSchedule
      containers:
        - name: mosquitto
          image: eclipse-mosquitto:2.0.22
          ports:
            - containerPort: 1883
          volumeMounts:
            - name: config
              mountPath: /mosquitto/config
            - name: data
              mountPath: /mosquitto/data
          resources:
            requests:
              cpu: "50m"
              memory: "256Mi"
            limits:
              cpu: "250m"
              memory: "512Mi"
          readinessProbe:
            tcpSocket:
              port: 1883
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe:
            tcpSocket:
              port: 1883
            initialDelaySeconds: 10
            periodSeconds: 10

      volumes:
        - name: config
          configMap:
            name: mosquitto-config
        - name: data
          hostPath:
            path: /opt/mosquitto/data
            type: Directory
