controllers:
  main:
    containers:
      main:
        env:
          IMMICH_LOG_LEVEL: debug
          REDIS_HOSTNAME: redis.apps.svc.cluster.local
          REDIS_DBINDEX: "5"
          REDIS_PORT: "6379"
          DB_HOSTNAME: pgvecto.apps.svc.cluster.local
          DB_PORT: "5432"
          DB_DATABASE_NAME:
            valueFrom:
              secretKeyRef:
                name: immich-secrets
                key: DB_DATABASE_NAME
          DB_PASSWORD:
            valueFrom:
              secretKeyRef:
                name: immich-secrets
                key: DB_PASSWORD
          DB_USERNAME:
            valueFrom:
              secretKeyRef:
                name: immich-secrets
                key: DB_USERNAME

immich:
  metrics:
    enabled: false
  persistence:
    library:
      existingClaim: immich-pvc

valkey:
  enabled: false

server:
  enabled: true
  controllers:
    main:
      strategy: RollingUpdate
      pod:
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
          fsGroup: 1000
        nodeSelector:
          node.hardware.gpu: intel-igpu
        tolerations:
          - key: node.hardware.gpu
            operator: Equal
            value: intel-igpu
            effect: NoSchedule
      containers:
        main:
          image:
            repository: ghcr.io/immich-app/immich-server
            tag: v2.6.3
            pullPolicy: IfNotPresent
          envFrom:
            - secretRef:
                name: immich-secrets
          resources:
            requests:
              cpu: "500m"
              memory: "2Gi"
              gpu.intel.com/i915: "1"
            limits:
              cpu: "8000m"
              memory: "12Gi"
              gpu.intel.com/i915: "1"
  persistence:
    backups:
      existingClaim: immich-hdd-backups-pvc
      globalMounts:
        - path: /data/backups
    encoded-video:
      existingClaim: immich-hdd-videos-pvc
      globalMounts:
        - path: /data/encoded-video
    profile:
      existingClaim: immich-profile-pvc
      globalMounts:
        - path: /data/profile
    thumbs:
      existingClaim: immich-thumbs-pvc
      globalMounts:
        - path: /data/thumbs

machine-learning:
  enabled: true
  controllers:
    main:
      replicas: 2
      pod:
        affinity:
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector:
                  matchLabels:
                    app.kubernetes.io/name: machine-learning
                topologyKey: kubernetes.io/hostname
        tolerations:
          - key: node.hardware.gpu
            operator: Equal
            value: intel-igpu
            effect: NoSchedule
          - key: node.location.type
            operator: Equal
            value: remote
            effect: NoSchedule
          - key: node.role
            operator: Equal
            value: edge
            effect: NoSchedule
          - key: node.reliability
            operator: Equal
            value: low
            effect: NoSchedule
          - key: node.workload.class
            operator: Equal
            value: cctv
            effect: NoSchedule
      containers:
        main:
          image:
            repository: ghcr.io/immich-app/immich-machine-learning
            tag: v2.6.3-openvino
            pullPolicy: IfNotPresent
          envFrom:
            - secretRef:
                name: immich-secrets
          env:
            IMMICH_PORT: "3003"
            TRANSFORMERS_CACHE: /cache
            MACHINE_LEARNING_HTTP_KEEPALIVE_TIMEOUT_S: "0"
          resources:
            requests:
              cpu: "500m"
              memory: "1Gi"
              gpu.intel.com/i915: "1"
            limits:
              cpu: "4000m"
              memory: "20Gi"
              gpu.intel.com/i915: "1"
  persistence:
    cache:
      existingClaim: immich-fast-ml-pvc
      globalMounts:
        - path: /cache
