apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ollama-internal
  namespace: apps
  labels:
    app.kubernetes.io/name: ollama
    app.kubernetes.io/part-of: home-cluster
    managed-by: flux
    environment: production
  annotations:
    cert-manager.io/cluster-issuer: root-ca-issuer
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    traefik.ingress.kubernetes.io/redirect-entry-point: websecure
    traefik.ingress.kubernetes.io/router.middlewares: infra-redirect-to-https@kubernetescrd
spec:
  rules:
    - host: ollama.home
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ollama
                port:
                  number: 11434
  tls:
    - hosts:
        - ollama.home
      secretName: ollama-internal-tls
