apiVersion: v1
kind: Service
metadata:
  name: ollama
  namespace: apps
  labels:
    app.kubernetes.io/name: ollama
    app.kubernetes.io/part-of: home-cluster
    managed-by: flux
    environment: production
spec:
  selector:
    app: ollama
  ports:
    - name: http
      protocol: TCP
      port: 11434
      targetPort: http
  type: ClusterIP
