apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: apps-pg
  namespace: apps
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:17.6

  storage:
    storageClass: zvol-local
    size: 15Gi

  affinity:
    nodeSelector:
      node.storage.mount.postgres: "true"

  resources:
    requests:
      cpu: "100m"
      memory: "256Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"

  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: apps-pg-backup

  managed:
    roles:
      - name: nextcloud
        ensure: present
        login: true
        passwordSecret: { name: nextcloud-pg-creds }
      - name: authentik
        ensure: present
        login: true
        passwordSecret: { name: authentik-pg-creds }
      - name: paperless
        ensure: present
        login: true
        passwordSecret: { name: paperless-pg-creds }
      - name: mailu
        ensure: present
        login: true
        passwordSecret: { name: mailu-pg-creds }
      - name: roundcube
        ensure: present
        login: true
        passwordSecret: { name: roundcube-pg-creds }
      - name: airtrail
        ensure: present
        login: true
        passwordSecret: { name: airtrail-pg-creds }
      - name: cloud_dbeaver
        ensure: present
        login: true
        passwordSecret: { name: cloud-dbeaver-pg-creds }
      - name: outline
        ensure: present
        login: true
        passwordSecret: { name: outline-pg-creds }
      - name: jellycleaner
        ensure: present
        login: true
        passwordSecret: { name: jellycleaner-pg-creds }
      - name: homeassistant
        ensure: present
        login: true
        passwordSecret: { name: home-assistant-pg-creds }
      - name: memos
        ensure: present
        login: true
        passwordSecret: { name: memos-pg-creds }
      - name: guacamole
        ensure: present
        login: true
        passwordSecret: { name: guacamole-pg-creds }
      - name: vaultwarden
        ensure: present
        login: true
        passwordSecret: { name: vaultwarden-pg-creds }
      - name: lab_staging
        ensure: present
        login: true
        passwordSecret: { name: lab-staging-pg-creds }
      - name: progist
        ensure: present
        login: true
        passwordSecret: { name: progist-pg-creds }
        inRoles:
          - pg_read_all_data
          - pg_write_all_data
      - name: chemistart
        ensure: present
        login: true
        passwordSecret: { name: chemistart-pg-creds }
        inRoles:
          - jellycleaner
