apiVersion: v1
kind: Service
metadata:
  name: apps-pg-rw-nodeport
  namespace: apps
spec:
  type: NodePort
  selector:
    cnpg.io/cluster: apps-pg
    cnpg.io/instanceRole: primary
  ports:
    - port: 5432
      targetPort: 5432
      nodePort: 31010
