apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: nextcloud-db
  namespace: apps
spec:
  name: nextcloud
  owner: nextcloud
  cluster:
    name: apps-pg
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: authentik-db
  namespace: apps
spec:
  name: authentik
  owner: authentik
  cluster:
    name: apps-pg
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: paperless-db
  namespace: apps
spec:
  name: paperless
  owner: paperless
  cluster:
    name: apps-pg
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: mailu-db
  namespace: apps
spec:
  name: mailu
  owner: mailu
  cluster:
    name: apps-pg
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: mailu-roundcube-db
  namespace: apps
spec:
  name: mailu_roundcube
  owner: roundcube
  cluster:
    name: apps-pg
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: airtrail-db
  namespace: apps
spec:
  name: airtrail
  owner: airtrail
  cluster:
    name: apps-pg
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: cloud-dbeaver-db
  namespace: apps
spec:
  name: cloud_dbeaver
  owner: cloud_dbeaver
  cluster:
    name: apps-pg
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: outline-db
  namespace: apps
spec:
  name: outline
  owner: outline
  cluster:
    name: apps-pg
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: jellycleaner-db
  namespace: apps
spec:
  name: jellycleaner
  owner: jellycleaner
  cluster:
    name: apps-pg
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: home-assistant-db
  namespace: apps
spec:
  name: homeassistant
  owner: homeassistant
  cluster:
    name: apps-pg
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: memos-db
  namespace: apps
spec:
  name: memos
  owner: memos
  cluster:
    name: apps-pg
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: guacamole-db
  namespace: apps
spec:
  name: guacamole
  owner: guacamole
  cluster:
    name: apps-pg
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: vaultwarden-db
  namespace: apps
spec:
  name: vaultwarden
  owner: vaultwarden
  cluster:
    name: apps-pg
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: lab-staging-db
  namespace: apps
spec:
  name: lab_staging
  owner: lab_staging
  cluster:
    name: apps-pg
