apiVersion: v1
kind: PersistentVolume
metadata:
  name: apps-pg-pv
spec:
  storageClassName: zvol-local
  capacity:
    storage: 15Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  local:
    path: /mnt/zvols/postgres/apps-pg
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: node.storage.mount.postgres
              operator: In
              values: ["true"]
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    namespace: apps
    name: apps-pg-1
