apiVersion: v1
kind: PersistentVolume
metadata:
  name: crowdsec-config-pv
spec:
  storageClassName: nfs-nvme-manual
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /var/lib/crowdsec/config
    type: Directory
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: crowdsec-config-pvc
  namespace: crowdsec
spec:
  storageClassName: nfs-nvme-manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  volumeName: crowdsec-config-pv
