apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: crowdsec
  namespace: crowdsec
spec:
  interval: 1h
  chart:
    spec:
      chart: crowdsec
      version: "0.24.x"
      sourceRef:
        kind: HelmRepository
        name: crowdsec
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    _collections: &collections >-
      crowdsecurity/traefik
      crowdsecurity/http-cve
      crowdsecurity/http-dos
      crowdsecurity/postfix
      crowdsecurity/dovecot
      crowdsecurity/wordpress
      crowdsecurity/nextcloud
      crowdsecurity/home-assistant
      crowdsecurity/whitelist-good-actors
      crowdsecurity/wireguard
      gauth-fr/immich
      firix/authentik
      Dominic-Wagner/vaultwarden
      andreasbrett/paperless-ngx

    image:
      tag: "v1.7.8"
    container_runtime: containerd

    lapi:
      nodeSelector:
        kubernetes.io/hostname: k3s-prod
      resources:
        requests:
          cpu: "50m"
          memory: "128Mi"
        limits:
          cpu: "500m"
          memory: "256Mi"
      persistentVolume:
        data:
          enabled: true
          storageClassName: nfs-nvme-dynamic
          accessModes:
            - ReadWriteOnce
          size: 1Gi
        config:
          enabled: true
          existingClaim: "crowdsec-config-pvc"
      extraInitContainers:
        - name: hub-setup
          image: crowdsecurity/crowdsec:v1.7.8
          env:
            - name: COLLECTIONS
              value: *collections
          command:
            - sh
            - -c
            - |
              ln -sf /etc/crowdsec_data /etc/crowdsec && \
              cscli hub update && \
              cscli collections install $COLLECTIONS
          volumeMounts:
            - name: crowdsec-config
              mountPath: /etc/crowdsec_data
      env:
        - name: BOUNCER_KEY_traefik_bouncer
          valueFrom:
            secretKeyRef:
              name: crowdsec-vars
              key: crowdsec_bouncer_api_key
        - name: ENROLL_KEY
          valueFrom:
            secretKeyRef:
              name: crowdsec-enroll-secret
              key: enroll-key
        - name: ENROLL_INSTANCE_NAME
          value: "k3s-home"
        - name: ENROLL_TAGS
          value: "k8s linux home"

    agent:
      nodeSelector:
        kubernetes.io/hostname: k3s-prod
      resources:
        requests:
          cpu: "50m"
          memory: "128Mi"
        limits:
          cpu: "500m"
          memory: "256Mi"
      env:
        - name: COLLECTIONS
          value: *collections
      acquisition:
        - namespace: kube-system
          podName: traefik-*
          program: traefik
        - namespace: apps
          podName: mailu-postfix-*
          program: postfix
        - namespace: apps
          podName: mailu-dovecot-*
          program: dovecot
