apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: crowdsec-bouncer
  namespace: crowdsec
  labels:
    managed-by: flux
    environment: production
    app.kubernetes.io/part-of: home-cluster
spec:
  plugin:
    crowdsec-bouncer-traefik-plugin:
      enabled: true
      crowdsecMode: stream
      crowdsecLapiScheme: http
      crowdsecLapiHost: crowdsec-service.crowdsec.svc.cluster.local:8080
      crowdsecLapiKey: "${crowdsec_bouncer_api_key}"
      crowdsecTrustIPs: "10.0.0.0/8,10.42.0.0/16,10.43.0.0/16,188.134.87.62"
