apiVersion: v1
kind: Service
metadata:
  name: bulwark
  namespace: apps
  labels:
    app.kubernetes.io/name: bulwark
    managed-by: flux
spec:
  selector:
    app: bulwark
  ports:
    - { name: http, port: 3000, targetPort: http }
