---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gatus-secrets
  namespace: apps
spec:
  encryptedData:
    TELEGRAM_CHAT_ID: AgCRuNazCGrrNhIvXSXcHSXbhAtvB0eCVxfHXMpo1SkyAa/Mf5/Fh0y9mnYUYI3jZuwlxABCpv6cYLOcjKmuC3uE5wo4fNADRg0RgySz2ZwXc9dLD4GSqN4/0tC2N/XQJua8qGuuho3nekAnIIorutJ3YPYDrZDh59t47nR+uq2wejEMIC08H+bVcPY7jRypIwHXhKPWQEvhfTDkpvEbCIW+uEhd/qa0WspNYAcmqPUfMUeHw4h3NTT7KDMxU46UdbSh94Fhl4xgnNkQCju/6GL9/UIy9ukxoBxmZlqOF6B3RT9JfX6HXPPZHazaqSFZHkkDfswxWEtZVt0ugIRgcGu5f0j1e013yzN8wQivpMYpwubqQ1IFrJkl7SxP2U7XJJt5m0Ui3RnF6tBUhpGkcP2A8zxLK+7/WdpBEPlLViKhhp8N0mHpmeqa8heNu2LD52slp9WwTXiG2IYylVZsh4/aqEeJZv3wCd+6tAYUqAVuNEBTy5eSdPu9HQDk2CkSYWsYcYqVy3Z5cf9O6rSyX4V+A2iCYj+Ju8G/MeIkXY/9n/qbE19GgkzftkfWXF59kb0UfnEpNtq7VdzGFLOPMOBIhmJzzclsBOIQk+eH4QpEAyGG4Rgguc1XO9MhHAq4zpCmJfvTX7jWIC5w6EJZr9Awgi2U+2f8S8bkPg5OgyDMulfHUgt4olPp0JqFzKSGoZshiGH0KAesNQ==
    TELEGRAM_TOKEN: AgBIeRSXkFH76VN508xegRciPNdcNaYQzf2kQrtb0pbwD4xPniiLHNtVKbEGISncuSZkZUNy9MGqTlZ9bDd3SdjLsUTh9KC/3xPj4qwTibnt11XX7Sm5i/DUT0AmTipuKyvESpTqTgVHgv8eEIZU+QThk7tGBvVcC/UgFGvUodCntJptWUJulr+txLtCxxhJCbA61KlFMnRv973muuGOKd7+OWGCDrVE2byBH4cVWXkyq3vCFrPFZtHGUyXhcNpL5AEvHaqxN248kYdvcCuzYaq72p3DSnpmx26h8BbhH3tvoKBlCL0/9lyL1YbuFoL5w+svnGtO2FmLwBsnMwXsit9PYbUKw+ram8Lhl16jR+GxT3vdZdI63USDshVjl0jfsxX0mqOPv262tuz8TOX0bRnzzYjnDKVEViBTScf7luiHOpim7xeCqneu9GBY8KJ8wJ7KoWwKYBU7Z36fjGbxQ3hsTa2qYbBJx6chm4eiAQbcltRnCl1K74hDktRziL3c007cp9S/cSgkNAvskyjeuuNYEnuOPc89vZM2JCu41AzXuUhMvT9Osl0QncCHhndMrQAfICFY164fSlDjSQ1aq5W8hDQv4M+WFIE/RLKe/i+Mn/L2QQfcVX90fKLi9GV+ASnPhbJvf6DDwaKfMxKewgm2uhIcilHYVgMUligqe8qpsc2sxCv6nKIJ4/ijGafFqpCDcQG4QZbzzGUb8Ppz81iLbW2vvR9Vj0rVpkXc6AfJk/8rXi2UxpS26M7uazrG
  template:
    metadata:
      name: gatus-secrets
      namespace: apps
