apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-originals-pv
spec:
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /mnt/Main/Memories/OriginalsNew
    server: 10.0.0.4
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-hdd-manual
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-originals-pvc
  namespace: apps
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Gi
  storageClassName: nfs-hdd-manual
  volumeName: immich-originals-pv
