---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: renovate-token
  namespace: renovate
spec:
  encryptedData:
    RENOVATE_TOKEN: AgCb028wdOcMqLkRnG8zSOM5APdTRQdbBhtgObEAAyLKt/OjpSKlIUt8434sX40vY8dG9Gs9ndXluAxqCgxJZx5i/NY5qtRLoFjqmqeiB2nBEPPD+g3a+1gK2he0MZcFFN0FQG5k8u6B7jmXB6NhHeZqCnIU/D/oEvn6UVXHPwzoYRAIjSym6fQnex5MujUFvIv7bv2FHgxzbjd7R0q9sq7V080soco992gOSNehAnLeHmaX5ljkgjNNJhVKTh2VPc5igLC9eOro8oMHsqyMjVHgUSXnqtKRaVBEmrSBhfJvvaJXutX3axIEocxCxXBCxc+oFThKVydsSEcp07mlxwebUGUcbWUoLZcdDQSQFrgwNkM5U8MKPNfx+FoP0jTjqcsilFLHdARa1RCVUQcljqjbOtHwW1rEKdM3VVA81R38fK3p4kJ98FKf4ff/CFUl4Dsmmo2ijEfqTz8dILeHHH8XUjnkyI72Xd7ingm5HI90BSTpXRjxPrG3ZfclWfjPNvVm5FEJxRoFgtaG7beyvRF1V4eMghWjdl3YKFKUIPX/wjzLQIUXliUAIaquUgMZaosmRU8wgphVMm048uBEkijvBl/PEjQfZAs3iVepJEJcwWaaackldFCkCGm6lmFHVmeRt7vMxaavmAeyA3h+9tH3FEXd5JOJrD1J+TkGcSvneYFDU2pwI4/jRKibmCPp7G9ia9C9uExw5qsgwChmHvEDAS6Fc8gheF4zQ8nKacgmFXFlIo9//I1+qKoOq2WnREUeOSs=
  template:
    metadata:
      name: renovate-token
      namespace: renovate
    type: Opaque
