---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: renovate-github-token
  namespace: renovate
spec:
  encryptedData:
    RENOVATE_GITHUB_COM_TOKEN: AgBFbwJHDKCIROO1uhh43n7gSEo79hurqWN7ul6Zqs/XgbJPI8HnmS/V6WSAmOzggx5RD76n12SHra5EO2x/YRF4bZXmhpGd4tiZurzw/8HdnIgw42i1EvhVRreqgzevzbDKak3iZ7pEYdXedYPjJ3NwfvZwyDGLTQho1R9r6EYzxfYxZ91QtdKzEaxMBjqs0DvCK4hXtABIdX7ZgZQNyXJ66lIbw61gdS4+WrMsPzxVzrSsZLH9W9KZTWGLg6u05AyL5EvGsvOT8AzYMgos/dEr7QUQJf5LhpT+U7h9O5ntgSropy6nuWK+zE3PfFdEwRxPjYwxAPvHjC3x0JWv6LicgcB2mCD6HsLJZCZdwE+9oMVzH+lbal6G5erGVCvzgpm8QKXESLFw/guYQzjh7RGUsB//3x8Yo0XWhUhGMms1E0xKH8jhrVVCayriyRLCdUqHFqz7V5Olux8yz2wi0QKIFUoiVCEpT2JfJvZGOKKrv2IB80okKrFeRZHAIGqcs7hzstiMhM2HHkDAhTFOi5Nmrc+fxdBwPgjpRd34AwSrbFbQQX9IgaDZ1MLVqHU3/RfIUW0YQVXKwgJcQN0vXigL1MlsVTip0nv7Ia+os11U5qKb6vcVd5hD0+dPNXrKYNUn2Mp1ZsCRNrOEOIvqkzciXaDHi8iyVqZbZ4TtcVw5oNtBAN3j19s5roHAUeu6v7b5YXEQCYXnQANGhn5nApqy5HI9ubqItjjHETM+7s92pdfqs2qHJAnv
  template:
    metadata:
      name: renovate-github-token
      namespace: renovate
    type: Opaque
