---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: renovate-docker-hub
  namespace: renovate
spec:
  encryptedData:
    DOCKER_PASSWORD: AgAtoP3WjaN93nTtWwxGexVvCA0nElmzyYRD3rG0akEedifhED41yJVhIV1M7t5xN080TUplfPb+nGYWazOfQa6EX03j/KrnNxIUWbBOoXx7d0yCTXimPFLwczdo/FF9T5OItGpgE927sWCHIjGfZ1deOTF2sPaMpzZ6V08T84Ww0WC48m+QQuECfXkhFxYfiEeZQp7xpqYqLgh8DEmTuyvcGP0wlOAf6wc1xEecD1Nla5SVN8frtjzm8D0AcxKMmwYTSQossO59Wniu7ggc8yevbNneg0Y8s08kpdvwlPRpoXlXBsXv828JVbsxXnguiIZ/NPrGFsLZaLiag3uckmfzFVdH+n8ksrVqf07Ui60O3vvolMfihjl8NGY0yZ8SfJOMAJ+Xyn89BanahbAnB5YyznWdn1b+dWARZMydWhCfTLvsDjWONl/ocDnZDqSW+FO0TVo9Ak1LWGJqaDCrPL8maL+4LbnfK0nzEM3cerONAAoYnE6Vpznu1OzKIrL1IyhXaQP6ZEOQY1nllCObce4ySd37OSAX2ogQkfRRVNZoqVFa7CaDnrHwCTLlQQfYjYTG9+9cF6JhjkdLR4is2+RiddPiZMDxvSLk7t5R6orQNjYiRlSc+lXVxfPAd8CLQhB8cEdiYdO/waC2UhtJSz5GQ768GJ2MOlMBSzRBArDrVFKVNrnOgsrrcQtOEGPRkwwMJ6TgV7mKUGA7vtxbE73Z52a1DSFl1Q+ofSdR108DCaP7iHE=
    DOCKER_USERNAME: AgCBM4fKhhweupJRPuuqse+6PNXeCq3SqvaLBSCjaEqiti35Y/lYiXd0HSqam77LjP9GRCqNkFer+9rHcVR3PPibHGohXrHbRzfYB2AbW5LsQlCXSTQkb9BkPTr5p2owEKcWFOPLq2lvVvf5EOXtz2s7rWTNWmWtVhRr+fKP1QYB4LNvFY8AcMqbX3Nh2dkdPg+uAk9fUReVlz0JVAw1Qu18pDAvW/j9+og5FDsqJFQ3Y0TQrpyrWayVSxTdPCFI/JpuxjpTI5/8eKJ8tcqPoK0hN5UitK+JjjgcoiGmQOyR2ReMKwF7gF+ocLjc7bEhLykrCoD3EotpJGOFqKpK08+lM6CIfY5foLS1Oc/ll36lMEVi7y+BUJB+93OKWVGE7Ka/XMryikxFB3pyVh/woX07+Yt4X2IJYNlyxfLvmxa1DVHGTQdbwoIyDyl/P8dR2wFF4T/MOo3B+TsTd6PB6XOn0JoZA40DGzJwaguo0fk+7d6ZPQhGsH2l0S3tCqEd0QJYXVqVDl1sPC3ZBDWyG39ufUpXDbFG59jCYMtGIPSOAm5s8dQyWpd05I52OpS4iq7/uEZJDhYseg3BTVUxjeG9bRzpeO7HZ4VNcf8qkL+jDlqLbWch0HI6llqwOPm6pfrqB0DOcS9r9PT1nipfGIKpwX/5Y53Zt/B/lBRZIBJaGAoph9xhQHwPFG4mDrd8FLYMzZ4HC+Er
  template:
    metadata:
      name: renovate-docker-hub
      namespace: renovate
    type: Opaque
