---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: bulwark-secrets
  namespace: apps
spec:
  encryptedData:
    ADMIN_PASSWORD: AgCOL1BBJYUv3rSG+3qntMl/UeLJ6l+UT/K0fbdM2FelUM4erhVsQ/nNey+7mtgFEMiYw7MsMCTKO4QMXhdZbPJJ3F106ketHKdbh7vheG4h3oORnECDM4zpnB7/PwGErzPlafHeND8664egp88nZZE9mhBWWRUeLWlRWfC3LHLbXNHrzfBZbLrTTnnddeEGy7GvUdWQI8ZLzHiMEioHLGI8f21eVUfnAxuXifkuRZycKxD0XBJ8ZbbLaiMaaJ6089n8l5tGOfw+8hd2ifeN397yz7+iFLmJ9wp9pzn3v+3OJkkThPTtATnuMUhkvGHcVKno9LHNwOEPV/pfc+6MJnmNnVFODOX5mMalVaNMkdHd2Me/s8ppY5ZhhAczyeRr6jbjsPdY5C6swbS9LwN7Z1BVm7VO/n0/Zss+suyPYkoa0+7RPrUSFZ4DCQxsI/07ElO1KLgSU9JqT+L9TawrawO7Fh47ERscN1L/U/JVqCcHTh307b9mDiabeKfwwTj2BGJ2DUNSCXlZ44OnpacwcONMBhMkBoOKO31Qd5d8MVPKKCeAosA1tlrUDlyulBDUY27QoctvX85kzJtsRqr58oZa/mM0V6AsF0CSjyGp46bHzFyC2H4u8dq6QIBbd4CYHVY7xKDoWQ/i+HAtwA8TZnFrD4tHl+L0pA95meCs9Y6/HGoDFEDS8O2pcg6suBI7e62u/ia2s/vQ07IsmRxR6fehdFXcclHtjwd0vr9DrQjFfvuNtm81eqC9
    SESSION_SECRET: AgCCWcfKA4O2OgDMWMsfXmpEO4e+Dz/CRWwOP7eNXfEg2B6wEYSVPsJh6x3ZGyfTN3BuD0pCNfRepOas8iRwhz9DdHXtMpD4cSBa8/LDzKtXzJcWQbIlmkITBIXUo5+g6E8mS64FRnwZD1PSWmOX1IYTeOfYzWXOoTEKjZBEfZGWli4/ifzfl9jncy9RkBoh9S+o0c3BDaNmnOBNvwyGr/V73c95VOOSE2lTYwyeGJb7s68tbRSTiaticf1aKq2giubwdVsHdJmD9ZEBeSjJcslWGoUY/yOiKx5W1jkN73bm/26mHIWnQn86BW+C7E7Xuka1tr5a3R2cNEMp5Vb4rm/06hP9iwbOfQ57MHuQ8Hjd3zvrxZTeW3EqLOsNWIYtkXlrgAqLWx5EhxSYU9z9RByIFaXOrHfKclgoQaInu9T7tFpqDl9oN0TwpooC/AC4mNbiGroqmfr008YzgUKoM9KzoxevglRICLb0qo1oHKg6mKtC6MDXxC+jUq/oip2UvSrBnpSjIunwceWdLHv7dTpzf0nkMn0lHCqXTH/odQyyVfLZPyI3Ui4Hm8xoYO9xSbTkjEXSlrqRVqBSE1BeG6+BKfTSWAYvl+sAiSClZFcXv6bZf3Q08y+7GmYdNr5MsfYHD1xR6wk0Hk9/5j5dpo1WLx9VnxhXgBOUiUcbugE1wNhhQTb7q1o+c5E4V3bVIu+nd2uySrKm+Pqs5lNZdBCZ6IjuTDyFVS9wmSsjSRP1LvcboDdaa4+B
  template:
    metadata:
      name: bulwark-secrets
      namespace: apps
