---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: dr-stream
  namespace: parapar-dr
spec:
  encryptedData:
    password: AgBGv+wXLVGuhjJMr6fRHakrta3xaPbVwF3i+ewvqnvxmDyezaYEtE731nMO/Kj/PG9RsM/F8P1G0Hi2gddeOCMDLZt/LrHF9rG2n453nUgLEUE1ZbybpFxi6qevxQDaGZ6poatgIFureameI6RLZXXufX4VY1KlQ3Gg5WGy+5eLGlCriRQVK0pS+GF8/dza21n64SIvja7hRss8nu+F1c6uj1Za5T4HbPOLcctY70+lByhHGHiPhym/GV1TR2GjC1X+Mr3EJ05Bxz+UEsZlRuNrG72aqYb81wY2dI3sy8BD6+DxIXhwSu53u5y+rrzMSvjOMGjgJYk1SYFri5wxMabJ17E//q97a1VsZBRikkRUXF00Xu2gTqIop0U+aVF57Xw9oZsxDGBFrAqNn0w2bfFFhjifrMWnShAae3+5Q01MZFDy0GBOdqhm7IrIg8hstM/Wkoxs9tfOOw0Eh9QzKfXTP7prBp/GP5XlIPoUlHIELxaVu6aL6ZZLr5xtU2JTbfWI6znm6rpgfc2nmbRKckAfai4raKQqn3DrrJJc2/onUbMr8qp8SQm09w1MZfC5VlESZkF+qaeH1zMD397vUXL8ixOidQm61+23gY/hRvu04BvkVmA6gppHzcnDqQZ0PPZ8Mg6Nu3q1cMUywuf8wIkVNEhgDPlOAf2LuiHA/AGenr5NsAJntVjjWMVpOIRRtPswyWVjZBrvK9qbtWdfa99ZN1DN2/2ime9nKbHZOdfrzA==
    username: AgC6Cf3NAePJ/jr6BDpx2H4nMA3Sq5VNintMRK4hL5ToB39UvBtw3oYjaq2ILFyAmnsDnn4+1ABB6pu/XeYCsjob7weSmAE1mqryf+kUynLM1aMtBx/2PBp8hZON2dIVa7Hyhu5qvUe8OV96Fhcn+SKHoUnT21xbhhFELpa/fbPLiqzVNu8hhzKG8hIPtwxsoE2hoMolF9GHMEv2jJSgXOMHKPE6gyQyrcYv3eUEl4Ztk1JmBRiU2gGekkT8ew5jGpjixMepaWGXTiRVw2aFXbdNWRG6TMbg8irt31VCsznBr4JQA5eU/p2+ZqvZf09mN2s0gTfQux/q0d0lgItLgt6K/bYFx/MrOWAGcbIRv63NY+/6ZOtw90/jxFQ4B8Ui5kA2FX/51kRwahJ4FzCIG2nV3f88SH7r6IE/AwrBzRaFet5bvqkYFNmhv1tQaZNKCEy7u4s1bFJJBiRxB+oqniaTGSuZS72akGGfiDeewuBPbew2VkjVqxuzOaxpNjYS1PKWqOb43mhgBImkUwajZvBb07HYKi2i5Y9TVHyn4Xd6MCXMj9G5zWfqnNyGkm1/VMxqe8+KqOhRYf6uhefZILyO1JMWm+338kWshT7kJgns29IM5f33HIWVXrTTCe9Vvvj5Td7NWJKfP1EwTOc9KwbkFn7I+cA04xEKzYkYAt6ZdWEyF5tziSxtsAfItN2V5kDTkw/jD19Iua0=
  template:
    metadata:
      name: dr-stream
      namespace: parapar-dr
