---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: parapar-minio-creds
  namespace: parapar-dr
spec:
  encryptedData:
    access-key: AgCMwncstXW7R5taqhS9uCU7zSfEc9Jo1JI49YSjRSpTLoeuQTkWHuuehUd6J+uUUfJ6QrH21va5CW73fSfyeLi+Ydfcg5PkkQDNEF3AVlhNdm2sPOpXLjfqDdd7IRqAcByRWRHYaMGzcDs4G4LYdqfX3hguvPmgpb+vWFgqxsWl2btxPrR/FVGMHwL/Qnbhb2ISeyJqUmeFnsD0/GQt72WxiiUbgyxTZONkaivOs+hF2Hqglv3vrbjUHg6l/N3Q+YF5TVBA+PczNVdG/53svypWv7vVfbGKhGeTel3D5+HUTa1lHx1PWS5Zyl/7teR4jO4jkvuFJDy93C2mrA7vdKPsqan/S3uQSWkG+C/Z9GZloc2pPTO1CdgW7fQ5cZ+0D9/ul4tUZMDDb6OJoBx7ywRm9K9wI/x+cL0tzPAvZnlghw9R6snJ4pl+4LcyITeIKU4WKo6J+CkIstcUoWgFLdjYGeb97twsG/3I/+5QZx+BZ9CfSLmo/ib+WlThVHaSAtMzMeYk8KwE86MEh1lbgh/Z3jdjHoD7YC+Ll6YC0L3CD6jcBZ7Txd7WHWz62a7WWSpsn/MTJ3r8ghs3K8K3qGH92hdBfxHm9VH6yC1SNPbz0vzoPQek2kjFpgmiKMp8q3JcGEaOZepc+d2RkauwmxgcYWGIKtGrCobkzlKFjJXtdoLOvbkYbv18LPJGQ6cg3rjDHIP0eA4g56TeFLg+SMY=
    secret-key: AgAkn5stXb7ruxeZnl4ywYKJClkUv4SInWFFETaqhusZy+OvxbK2HiYu/A+39vU5c248drjpNs5CLooQzMqn2ev4HID7x+jf0teJRYNFLFstAdswWWvqsBbspuTGxri5s3xsVrVYDOq8IegQ5W3qoLFFxgnkVmj9LXIBYMQkcerNH1oUNswrxHA9Wpzbm1hDZSRJAhtY0HqvcEbpUbZPEMBV1PniWmnoPgAmEEAxsCHAW9BIqgtQsg7pgg4aMr87MTI5/Es7bRCb9QYlLutSjzvhZddxFjZjS7HhoyZKM2m8eGijgn4w8xP5jSOYpzj+rBOivaQKAtGDkRjXRhkgw21i7lb7AMFPEcwbN3W++6fLJSYklaXFEEn0lKNmltOpmOiCTDTGExX4tCQb2Ho3t2KT18UrlAAh89UIvwH5J/EOVhVHPLG6CoW8HOg1z5w5k/DM1OdzlrnvaJFw+DW+5FB4Y025GvjsBE/2lTUIfdjuO7lw+K7mdtkrBd92fU3Qu4fvTFY/WlBIMND4BQCGaGyL0dYchw6mCg7f24RD8BA+WMO8Q/swsvY1gcT512TrxV4mGn0oUIE8vsRxN7iWj1alHOWHn4PE6cKpwN+ql56LfKpzaAYu3C8ULzqqyKyAMYnzgqkGRtc/VI7ym4JZ1Wm+ZjYjxuJlH8zNldlhNzZjuh+1xnOf2zTB+ME+ggEoJeY9Ms6TnIL2S5vG5pIbMI0nYQJAKlrEZq8EuDUnbn4ykEGi3GgGfo9d
  template:
    metadata:
      name: parapar-minio-creds
      namespace: parapar-dr
    type: Opaque
