resources:
  - crowdsec.yaml
  - cert-manager.yaml
  - renovate.yaml
  - apps.yaml
  - infra.yaml
  - metallb.yaml
  - monitoring.yaml
  - gitlab.yaml
  - gitlab-runner.yaml
  - homelab-bots.yaml
  - jellycleaner.yaml
