---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: crowdsec-bouncer-secret
  namespace: crowdsec
spec:
  encryptedData:
    bouncer-api-key: AgBDLWqR87Bp/hKPpXhZNmOLG9ajnHPVz5tpmhhZwv/9PhO3MjpQswGAZpI6avcWkArKieLsCh9qxakCwmjvS4zkZb2rurLwYQIN5CSCrScOpU2ucH2HI7DfWLSyl9fAqItQLmRdN8LWvf7ZS4o9b7vYf69n8NuuuHhQwN/c8aT5M3PWVxcM5NDh4NKZtBX68Q+v6WOMasUCOWNHtTJqNgcLZU5035ob87gWInckqmm/Ok8Pz8a/LyywnHq3+S5qEIAJOB+NF3RX77itVwBD+M+iDec4BUKz8SFNjneaFshfy8WMF+1Hgjf2ByYdxp0quM00T15wWMpH6AkNeKRRYRra9L7NMxmr8bOhmG1qjrm5YMHn7So3KNTESvqvjdXe364onx88WHWIjlrR/QeCTUguzW+vhnsmKgF0DBi2DhLbWKNs3amq09qSG/RN9BbOea7BaeszwtVOKbjfbhn4+AM86F0LsB+2Vh6JBnjI3d5SCuxDS7G0dw8GX3p1hvE8bBxAFkPnOWSpoeqv7XIgDUeKdN3Lc9dssMvmhrIJvG0ha4NqBIWu+0Fu7sP30x2km701D/Vczfm34K9/6JEs8kh+NjrN9pLr7nRFsf6KBVOysmzqW60PsIFX4km2P700VNyxqtPnjiULvnhjA7x8GpRoSva+6kAvHtH5oHdsTdRVYY+QIJp3dk/Qc4gkRgBZ4E/RMkjU5oOeKn4hyn2BVhUdjmfTrBnswMSBV/1RJhqkjIqju+j3RPsMb7fJaNDdVgiMG66ogj7EVc37LPOe8Xv2
  template:
    metadata:
      name: crowdsec-bouncer-secret
      namespace: crowdsec
