apiVersion: apps/v1
kind: Deployment
metadata:
  name: uptime-kuma
  namespace: monitoring
  labels:
    managed-by: flux
    app.kubernetes.io/part-of: home-cluster
    environment: production
    app.kubernetes.io/name: uptime-kuma
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: uptime-kuma
  template:
    metadata:
      labels:
        app: uptime-kuma
        app.kubernetes.io/name: uptime-kuma
    spec:
      containers:
        - name: uptime-kuma
          image: louislam/uptime-kuma:2.2.1
          ports:
            - containerPort: 3001
          env:
            - name: NODE_EXTRA_CA_CERTS
              value: "/usr/local/share/ca-certificates/ca.crt"
            - name: UPTIME_KUMA_DB_TYPE
              value: "mariadb"
            - name: UPTIME_KUMA_DB_HOSTNAME
              value: "mysql.apps.svc.cluster.local"
            - name: UPTIME_KUMA_DB_PORT
              value: "3306"
            - name: UPTIME_KUMA_DB_NAME
              value: "uptime_kuma"
            - name: UPTIME_KUMA_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: uptime-kuma-secrets
                  key: db-username
            - name: UPTIME_KUMA_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: uptime-kuma-secrets
                  key: db-password
          volumeMounts:
            - name: home-root-ca
              mountPath: /usr/local/share/ca-certificates/ca.crt
              subPath: ca.crt
            - name: data
              mountPath: /app/data
          readinessProbe:
            httpGet:
              path: /
              port: 3001
            initialDelaySeconds: 60
            periodSeconds: 10
            failureThreshold: 6
          livenessProbe:
            httpGet:
              path: /
              port: 3001
            initialDelaySeconds: 120
            periodSeconds: 30
          resources:
            requests:
              cpu: "250m"
              memory: "320Mi"
            limits:
              cpu: "1000m"
              memory: "600Mi"
      nodeSelector:
        kubernetes.io/hostname: k3s-prod
      volumes:
        - name: home-root-ca
          configMap:
            name: home-root-ca
        - name: data
          hostPath:
            path: /var/lib/uptime-kuma/data
            type: DirectoryOrCreate
