---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: readmeabook-secrets
  namespace: apps
spec:
  encryptedData:
    database-url: AgBKkzEF1HAs6nGz9LEkLrFsTr07IxyyHuod9rRZT9Pf2XQAk3K86gRIBK9JWpLf+WmoMS+l1Po5JKhTos3zjbHLz+e16wUQNRXHOg9CFFgujLmLTpe8BO9mRiHlvw7mnpe4vYj++aZfIvkk5ZgOn/c9Gf9Qqhr6np4XaJ3vvdRs9Q0/cbzekwlCQ1hryw+RHVQx6b+V3L7p1QkUbnElXW/hk+mlhjJ2teD4EHbJxYcAngjH5XbvC8sRoIU8q8wr4YPSD6ZXsJu+Ah5m6/nI8griVYOUpbJt2dz9hHMpQndTgUSdJtnXNnTXQmdkZLIV+0d3IjzzwSUmEAqACB35TR4cW78OBxVqIbYdk7Bpx+XMnLtvuqpynTu2w9pbRzsIgWJqSOsL2iFvDBznFBhj48dBSzLBM0gmHLBq+xlSurx9Ii1ce37wfY0S2XgQj2UQmrYs9UbOQACSPo+cgqKRE5uVTg/XuwrMc7jZhbhSzOrt/JnEIPFn9bAjD3ZyrPg2FwhYkOjDn1pcZ/bl/wmM9joF6tu8J058+F0WPdSC20WjW/o1+uI+dImA8RdIoKs5017WRiwnjJfNF41MzqSbV8E7N0kVaH7ozNUmgXXs4xmTbHTZfBJeapY5BLNi64XSdlfwY6mgJO+LaR75Ub2knCxZ90cnfTerA2dzyzEkoLvzhWiDewDB4XvTvMuNSyveOtH1F2j2eQSLMRqX76rs9EeTMLsrCrNDU0pVoXYjq+ZWWoaDOPjcZAeA2UrImsWeSG8S/d9eupoWzhndOJOrnjvYk1BZ3C4t9CRSMUMt4WJQvxNAiJ2jLxwa8iQs+5SFxUSdHrGQs+DpA9rz
  template:
    metadata:
      name: readmeabook-secrets
      namespace: apps
