---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: lab-pages-archive-minio-secrets
  namespace: infra
spec:
  encryptedData:
    access-key: AgBFQayomGQxvHvrHGWBNxSn7wjO2wYbxiStc5xWLfz5BAqelXNDDBPqeUC6UhvpOwjYZ2vL9zEhcK0gEWIxVW2ZpvwJ3Ae2leKClZxoUMwrvLVFmHru+xbRvGNaaWN1deJXe/AWTBOhZs3JY0sDlVnBZfQ7lwXFX6pebQP2++awE7fRe5wP2IjlkfI8Obv4Gn5ul3rofaH1/eu5Kxve4KncB+rT07OTKdFHGvIhhKg9dpcuJ0bxVzg0PDPiNEtoLJljIfzGwsv2g6I5HhFVWYfSP6EFMg0Gx6wmt0Zec0XIArW2cuKNaWRh5gQ3TFTcISeCdnPqK6oKyWSG0DAyJGQE/onrb3Iq4UxUZwNWQ/IAYbT7mGNM8+H/xoi071AwTRKQGBSdfW8+onsM8i1qc4zVsZ+MYBwTsbk+uzdC8pJC3uWomrcXugKhqBq+qxIzfM4u0JW6TFyu15OBI0aGs5MibRF6JBY6XN7PKzvTuJwZvNHqH5ScZPw8A8fwPNlaM9WFGKgAW/PrU5f1uRe85jy7ZIOQ9WST6c31yGvNZngdUSoucHPA7a5moRPyZ9PQmCkHIgIc/so3DHDQ1ZOrS1TT7V46QphBaKe0ieuJ7nM2urU61xjkTxaFgEx1QQM8ZT62Kmzw9wsdOpX1A7usQaJ1YD7aelv8++WQgSoee6mcj0pzGMmQcZqGt9hJ/Iz6qqVAMSUwQytmVrJ0uX5XoTtRF6inBA==
    secret-key: AgB45+62htK2BJQHlyqHD2n+677F8eEMmg2DQ6qnd7VmP+gdquBDfCkpKp/f2tRzJKNypAY5+W6kCQmP0GBqTkl9qO/nGX7ZdRtmcAkmT+NYtCMuZDtovOQdisPGuJEv3LjzZmhE95YvoOKrvDTxv9dnZD14w6QAClEUlLwaVkxOfvGkQsiAntmXd/ec+q5OgCkBbXY27/XZF/lFNKLnTIxbGEgICJEMHcR+p8OEvtiDe9oa2M4lONSmgyRSdvRb92vDiqvSae+fe/CyCsZ4nMo6PX7wtjxr0pt0BT+g1ErbLzjdKQgfqOG5o911wJudOhVoGghC9tUrECTG/z1wuopxBoOpwhkNjJPXeV0xcUfC8HS72qPuJNMwpF2M0tBIj/RJ0Ssmr0PoQSWzPq4euO7jefPkpX6b0ePvk+QM+WUICBWFkBrXsTIa6ykIzRgCAGgzsTMAXv7gz5m8/5TapXoiZNALuMhQDpCPH07xJntCSt3NTuPnuvMKXYgPBKkP304teDnip0PkBv2HO5XJl5vV/dyGyuibV7+KKdyLJ6J1hCCMlayoQtkR5+ZsnWQADXJ7zPqCRvVNNSeMDmKlqeKSxIV/j/CqLSQIuSjmw1O1KH3lBKAJJU6t0++J28GMHW5SuG9/cgq2XZewqYR+fOgxXfcKdBBMjx/DuQ35Iyzbn+xMEsbxWayx+kO+qT7tj9gdFWDXnjXhcXa8cL093bcY9BgvAlJsZZ65+Lf0iJMNHVACybdTRXlRAbEH97+ctg==
  template:
    metadata:
      name: lab-pages-archive-minio-secrets
      namespace: infra
