---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: parapar-minio-secrets
  namespace: infra
spec:
  encryptedData:
    access-key: AgCeifPGdVBIjvjoxc/edDeEbXNlfhiEOOtNpwPdgIgoBw/XHcH8MedW7Iu37KVPMJEJ16gME08x58vGWwIb5Kem0aHh84grSJk1fOfuciUvXiwOUdPz9SAloo4Ax16pBLfHWD+cbA/vstg9RPU0Z+LBgC1FBj+AlxHlaCrjUa2LJuWGZJqdnYb2rm47kAW+yyxXUX0ccdrSHRwDdizTsK+WAPz0q42KjnXsjWbwiT7UGOO+3wwjIUmufscpwlKugLgJ8xcknfd0AJiFKRqzrnKdrzn6l9j4R9FMhqJaqV9c+gyXFVniJItLW97BNT/HzJg//4mEfza/EUiBDQCSkApRV/mDk56nRkF30oB8Zs1UbuofyTtgQKO5Q+gIipLykHvX2i9kPpWs4m3z7g9W/FLWtS3+wTVjV9So4YF54N7rSsrkNPz6NZ7+T1YyE17tm8L+x3vdSIph8U13va0oEIitWgcSO/WdqXC85+X5tZwcyVFt25irAib22Jdfa9UTJoMNyTztWaDyJx70/Pf4PRG5Es9MEHACJ7psuhJMA9gLWFOKrJFCM3NYJiJBHh1Fq6e+7+oCkn4jZSO0Qs9xSUO844VPxj0v1pfNX/HIohTEx8ljbG+K7ep/BZEy5xqFig//iTB0eAv2ruwx80Ud2EGUA/q4Wekug6nH+vMMVBtb63e95bNJauHvFIBtRtmtsNKKMabe4WJT4ZfIVkQNFCQ=
    secret-key: AgAJSYrw54uel2m7QXoaEw2IqiFQQuX7pqG0fcL93J8HuQFsMJeRv6YUYyBjZlUg0Ju+tYm6vULaXoUWjBn0be+a1gMgTHIywg8PM9XHgvga5NOCHhijQk73D1mX0dOeIRN4hJRe+3EsbmZg2fcQaILYh0t02VdEfVUuBIyLVS9T4Ck8GuiUXthcL8uDZt+CfAWLhA/bKRKYz8nzq58S2BsleuaX/sHdzI4DwkgfYzuTo3GzWMozImpTKJBSItmU6lLJ71/hbm1/Sv/0BJsmab48AnvTQFosOFXCv+szDDvLanZjV/ePCkjOKRAkqiQZ6+Mf8q58MrAATOPYBLWDKKyLAPmVmgrI0QOsOubfo6RQ0D9CXbSwPPdUNd12l6aqfSjDBd+HXjPWeaFPiTtZ9zv3UqB0QGf6QDuzZsZ7LRPpp2pAmnAvJTquvlj828cHQtdjwJTFQFJEgIOUhJkmGBQjjZcWcItDsdXimoRBfvDJ4oCbaVX1YC09i/yOHjJ5pZXtyMQyi52mjjGvZ1bxXFncMy6zrUBbTRqZ1X2fAgEOUN+tDGyF0QQioCjiZeJMdWhqKA9FUyTYMgVEX9p5WJVX4vYIAP+F+FwjCzbYdo28j4Z2EgIVQqzfZi4+m91Jj/wvzmwK9dxC9b4Ru0C4PHsancg4A4v9yJSkN5bRcpadLjFLMA7lxJ4OK46Tq8x7JcYMjxT/qG+mq3HlXI35pAqqoTvGQGBwihin9Hp49vkgSyQEbTsstgiC
  template:
    metadata:
      name: parapar-minio-secrets
      namespace: infra
