---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: speedtest-tracker-secrets
  namespace: apps
spec:
  encryptedData:
    APP_KEY: AgAlA+ammCRnP0gEaksfBc7+NIDFmgspTSy0bz8zc06nWyFkDB+K6V+mhEKvQlujgmqmMqau88Baf+DeFFl/3JcObDYqZqaPAZpq2ICsLy4AHr1GcKqZ6JU8yd4bHtrxTgZ7atHIHuWqvgdcYGkXAFX738aKUmUO3xmVWDeIGIcMfYpr9ycxDYqbUbBleljxuYOSfwh0DQFDA5cLrbbSKtQkHvR/1/65L81PNCu6aF3u9pfxv7SvI1OJ64A5vMPM4BF7Pcr9DHlQF4CizzzR5sVFjTCfeX16M3QdJBkR9xUvD5JtrSM0cyFcfCRrj+zAkegSDp5vPhJr714K5Q5ycxWMcB/06CMp0ancGH2j/JbcMh57F8XHJdKE1GUy36aOaLVAwhLvnIBx/ZNR2GwWkbK7b/SUtYfWvSOinoFH+GJoQVyJ9eZ4l0Z+qTgnbH6k3NyccTNsD+m81+J1HAEvOopSD9N7xOhN6nUe27HiCaMt0IpzIjeFsbmkBgTcVJiRj+nlkt6Yhu7SPn+UcgbFH3YhxVRG0KUH20Pk0NPlnDq2Gi269ECYVzu4atLeiYaXM/OrfFlmezzh+dKZaEScKCe+ELJFp5ydwE2ptuIZtYcDRhhVPFx1BVNXjPkTdBU6Z7sYnPRl7hLwhDCKwHoBL4GWTFFnhCR6LAZIxTsHsHm2ra6sga0aYFyTIt8yaFAgD7DZQpe8sUXl6vpc5YOUm7gbUzxQfcoQdQLdyslqIa+Ot6dRIXfNdWtnxPxA72Q2yJDqWnI=
    DB_PASSWORD: AgBGlkwYSVuTHSHIxsiKd1PQdnWj+d4uJNdfYE3fBmyDsRdchLlHMYlL8FwAbxUgXebbc0Gk9IQeojCPXnj58umN4XOviqGrZi3lrHwfZT1TUQzL1O2l3nH6eNNhSds4x8z7HcBW9iHUmynwYlWoIf2RPuChF6bIfBknQ1fhtkgLs5ajFkSEPUOE63Jl5fnu78KJzZ7jOjfLLk8UsqljUwwtmpGRepicxFitPkEuPZYpYJU7ThPX/z/0zPW6JyCn3ZJZgCVYtax9yBDdBSE/b2rl6ZM9aCy/Gst+r1VLOhDbRWyZcNjCZtmWyCwFLpDODzpiFSga8gvyvKvT3AXu03nvclVFoeS0kmjogb7ODrVthyZSrZQwTavrlPwHfy/sFla4rJKFHImT4L6oQfTtPnc/SoCfqb1mjXQ3Y7Qsd83awqKGiyEWKs9LXYRyMG8W/0wE4nWLK7WDYY85V/IMMh/4jpW5bpU8uA0gGTTPOzJmXtuC3WRN8wnTRJNIclSh6g9RgapQPmyN6Rh9l8Vg9O7OBzOlN78SIOoqWtabohjjoU0uwPXov2E1PdGoQiYcgfdZ6zsFWZ3rgsCc4+zRxcSoyruYuR4dF9z3wsCC+bnk7kOBwE1ugBLwX/lhJUic4CCuL0yfURabpIKn6aiHiXImEMfKisI8euAkXlr4aq/38eTlvQ+a/QvJCVI+WcECcYlOYiUwYj4OVjqWzjqIAO2pfdWuRDc7Qq1slaO9hu3L/g==
  template:
    metadata:
      name: speedtest-tracker-secrets
      namespace: apps
