apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: novozhenin-apex
  namespace: infra
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    traefik.ingress.kubernetes.io/redirect-entry-point: websecure
    traefik.ingress.kubernetes.io/router.middlewares: infra-redirect-to-https@kubernetescrd,infra-error-pages@kubernetescrd
spec:
  rules:
    - host: novozhenin.ru
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: error-pages
                port:
                  number: 8080
  tls:
    - hosts:
        - novozhenin.ru
      secretName: novozhenin-apex-tls
