---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: airtrail-pg-creds
  namespace: apps
spec:
  encryptedData:
    password: AgBOUmzbhLv7dWeuMJdTdEaIx76Rq3q56dX99Ea3OfuG/Ba6uLXyEILDaWWWFC02mQUVFRSvsVLtt3/1jJKJtmCVyB1BZsoZOr/JZnfGf+hMCB/ZOX3akFp6JoTYolz4TPX5lne/+lxWQaqOmg7Ahn8o9Jj/EkCWFWvXdl586UBIDG0n5wiSXMdo9LVZ0EgIgQgnhctMrUepyCF5oZw4sT9/mj2nHdYTN3dmhuPoZb3FLqcOnctjgHUYVXFiM6R3PnzQpcJ6LOXFtPaJkYML6hreZKnO99m0YiLa216bo6ls9LiQKSuOkwDaQ2sAGjcCrBa12ukz1MqJd1OHZRV9uc28ofzmPamLZ4mJJtvUVdBUvEJ897jI7Ep1TQ1i829dbF07w3JDtPfvVJ4qX1j82tUU3z14m72cCR3RLHgqnGBbTycPkYsMpp7g1KMQg+hknp2vyp/DcbSrqZEsyDMfAcAY0tnLjcw0P1f2ytrCFTiJsvngr8BfymZ+kJ5QkfGStfuXWGbbzGNQ0GF7qmBohitkziyJrMG+wYeWkcKJstYaxwPo29188wvuPCajCh4S8rJygPRO3wDKem3tOo0QhvvIAIdpt9Lp/5Se8qL8DY/RKEaMULyQV1BlH2kbhRBN2yjUl5Ao3Szr4SlnnMgDyi1D4SXsG6+/j1/BhaPjDiR1iVjb6ycJ29utEH+5PzOfT5KI1nrv624vY+02PTIuYY+QjO8wxUPzLimSGfnnm43hdzqB0Wb+4bmVObU=
    username: AgATQ9UA3WPhQUfRHqYOiLRcV7tp3XPF//G1P3Vgp31m9MghBTH9wv1lrFonyjXnVTuXF+xfmcaRrbOHOe6uOwi/Gqhq4KwpTungC6dFPPQcFXUY6xqEJ/bCs0bO4A5qfNGjJz3P/W5+/eKV0urCNmcBXqrL3Nr15kCzbXVHOZZZECO7uls8mEWIp2U3bvKuFUqXDznyvNUUTVMyfxy4G9W/JZmSDO0z+2QAUV35DHnO0ydQfM/tIpovQJV6N0QSuG2/3PkWclca7qKrbRX/7fTH7XS8tu1gcpMymVZPkJ9wrJcHFm8ME2cpxAyoP57DfL+Vn2TOGJC+8S2kr1JBuyqi2NzL0jW4Li+mKNCLMVZUs/tLUlwtVopEwxkumhsepsD1WW1RmkuQRyWXfpEN+PeSe5lyBAAy6y5LylDQBVAwPggtDrVqax4bOAzCak7POCF+nddlajLd0Bh7btHswNG/tRFDPHaz13JlSKRqC4bGE1kOTlHf0X1Rvb8BQKgePumygbVb+x1x3ge/1ZZLaon5AjHMx1/Wyq0i2JUGWW3c5VV0YyKZMXVoUc+Asf/XtKyEWaNUZfKj58zSxUyA3kBYMB8nEwaRxSsa8F8b7Jk4n4nc3WXOOZOjf+oYi+MhXoLTxkaOuElTmv5v1s2XMLFwaz7BQ96/hvZlg3UUB1tk5dJd+5mHLlddPuAZEqm6ZDeaOtckY2salg==
  template:
    metadata:
      name: airtrail-pg-creds
      namespace: apps
