---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: airtrail-pg-creds
  namespace: apps
spec:
  encryptedData:
    password: AgCpxg1OlrmV8D4THL3QXkKHexZAIXNSUhXL5Jx62LYby5IQrhoUD7yhT3weAu78TYK16SwZ7BpiNUTiYyC/fyeAchQ0U/JoKQAvStC5OtQdPz4RAx96qUDtUlU1LxALjQY5PLPDGYQEGpeRE/4BWxO1ktUTdJ6t79rTQsmLtLYF7IcvC9egZYHdvDl2kgL8YA6Y8lqRHctxNYomZKBv/yQSYdk2W8Gob4iLufH0rJZIm3tumM+rs64SZtn8Yo1GNiHDQ1hoyaWQsS4vjawveFprYaWLrA4GnIsG1iqntry/uxXkvEEcWQLaaZCdZUbNT6mxERxfRNJDWtNc9qLObwK5/8Ltd3lY76ozzEr4NIU2rqqtqjiZxsiB29J/pzQCgtnBk5jywWZrK4J8v6Ve6Xn8O7yRnPQqy2f8i97/ehvbg+KMWs5SGIRWU8q4FN5wJQOTEso/2sGdImhSiescrFB7z9ruafLhRghknbVPmIlztoc6S5NBQMoHRiRjWAiz/LUGrVCOYADuRG/gq2hHb+iZILB586VyYg7EHq7gX+Tesp4yPtKOHLL8Ms8vvSNWc5s0VDKXECPCqe7T9eeFmP74g3cmZ9GTlAZmgm7/xx9hHTckuj00r6Y+h1lzOvT8nqw/QfZIKiPrGLQuy8P/l+4g7SwgxIrTz6xaFktOnvYc+svz0cXWlh49o0GeOjnGCvtAqJwNs2fo3DPNMDwnsGTOyCqYsD558NgZzzxBaexqsdhg8dyn4LGL/LCt
    username: AgBC61YLXHB+JH4DlpJNsR5KipPJI/Da2f3E/1NR7sIXdM4aIgmH7Z8CgnntfMck+EjEdWdGb/a51FYyHR1cVoSuA9gczfrUdCwg9OcrX8m/ehJcs0dmOWLqclHkCaNI2ghqd7RJgoAzlrW9dOC8XdCuSMu+izgC6BWc4o4JZSMlRo60xnbZpyCT6Nj4/Pq5b0Ltmn4X37wDmvY10wG6Z4gwyc2MHOXveuu2Jx1mQMXP/6pkUBDMhedQzrpfmX+/HBmoCreKoPB95oOyBmSzspwUkvPAmTs2sMOCaUZQ+jJqb5eQjb0E+WtaidxqWEGxorURW+0xFPQAo/fRhPKdUWRQr3b7IjnVdKJ3PhEzriXJSS2JVUMLObzrNPSeSrTgxO3LeV8gs0D3Lp7EoL6MGs4LueVlGVd9fkeEV+jvZaFOYj2yjtUq7VXZjtv8vLBzuX/js82slpihFSbFm4igPu0S/dAJbsKUpShaN/ot1Vbe0nGMTVC1/EbvQjf22V73duS/GlVwPtHIsh9sUOFK3db7yv8O5VsOHJiNZeU7ghBnmPhIRsqS70Qi+RYiUzOSIkBBY+DYk3e4TTTarR6AQf5RBRd1TUe3oZlh3ewLrRW9EGKGZqkmsn4algwy4C61u1ESz3IBVwS5mg/+766OXkewMemNvH2yP+S+bsUncTf3bLfS0XiC9JXw4+dDC64lyQ5ORfopfWPeAw==
  template:
    metadata:
      name: airtrail-pg-creds
      namespace: apps
