---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: apps-pg-minio-secrets
  namespace: apps
spec:
  encryptedData:
    access-key: AgCvKBQGsk2mUzmWQEuYn1Gd/yufYi3eEPjdhDE2uX/w5oOH0dLaN4YiamwqmsDJFY64ukzbGrquKLp+FRTDODO1pOLbqmCl0cF+DQQnpINU5CDaKFrTPE/wUhzi3S6PRvUIQ75MMzyWFHk5nTVj3KTImhfjFadaqaJRU1SMeW6zE+LdQtbX3B83zkkyTVqoVAl7FmFXc7iOhvh/Qi+RXiaHv+z1QcvBJLryfhZ2fdsSDTX/wKQsbdZYDX5ozXZ9aUmKvUU34xX9wFrKM7xih+atPXUXY7l/NcMJ4BhCvfTgTqnKu5DHDGdmXvZTJDAqQlviUM9SBTbmTkRJWm4PQn0l5MQXn6EtiTl+5GlEvP4fu1GTjNqSAEVoaZboskPEB4kNrtKfce4wyARl8kz9K//86ziFHyk65TRAOdRwmxycR4yexIy5g7B3ZLeTN3DfWJyUgsjZPifsYq1o9Ipo53XE/1lfCm8cf5pXqzXptrMHQLe2CK+c9cEIDfZP9FDXIZw03ynWeIQv3IfYDAe3/RyJIFi1AUyWrWNzlaU2Zy9GcS8Fpnf/CPIwb79mH4uE3c2iHc0OEqRAPeQ/F6j8WQ/2ZL4PmBebPFofGSquCLbRLsNeqtiFuSI/l6pYJbQb2pwlzmZzZXrnUsDxyVC1gIuqK/dybsJtUjC/6ttFYsixG5F6ozzH8RuhFN3girHMCELztQ0CQ+0ASosyE+7ewKH48EbCHA==
    secret-key: AgBmX/ms1J5sGk6sbhUaeTEJ5KLsTnhInFe0B8YsxTWrKSaFoDTB+zAKQgUjklJEc13XFeQxA3JechNV1x7P12D9FjMxL4VMusQwx11Zn1w6c4pLKYf3QrhzTLK8VMsPLbz4jdN3lMSJAANKdXsBdebzSVWL3u4htSKsyKt2Bcvf/+P4KGR1707FoNG0rHDG5Q+IXy4c76Gzr4fG+LrRqw5TUOuC8Vo5WI73RP9GZE4rH7+2Y9oIzMZcQQbv1Tcz2zWsCia5z/IskpzvRbitvMAZaNfEsoWboTKrW6x+9ipdD3U1F6FuNxcGoBu5ab01CJulWFLSQjmpcPNpuV/InWrfre9yIpiVsBa6f7MoxLnaQGLkddzG7W882jh1fPm8xzDM2kG8XSTqUoeTR0VdF2+XsRTXXAZB2IxLLCikaGua4dqwny7rJ/guH79K+QntGx33k86/rCe0kTnanIMctM5O+aH28L/jKMH2fLmSTq9y/etm7WwOfUKREV0ulCey+Jd8RRnZ7cb4MaIBQIEgKRQjlB2eo0mwcWzDruSns/uPZol2xqSw+TRxFbUfseutvwl3cxoqndCtqiMKtx95izM4osEAoqV2rcd3c9uk3TmfcCdBbKWrf9hWr78o/IudBqqL9sz+bk2+sSmSEKKsaEUNQDVB4/OTNdexpTdIlSjly/7UFj4c4qzuHrq5VUULJleuf3Oabxx82H2+8Xx3PUD9vfC3OXUFl91V9NY5wvaeiddEGCwOHOarZg==
  template:
    metadata:
      name: apps-pg-minio-secrets
      namespace: apps
      annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "infra"
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "infra"
