---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: authentik-pg-creds
  namespace: apps
spec:
  encryptedData:
    password: AgAZ1KkVdkUR28Nrx0qu1iA24eWhC3mYcVIuy+XW12SSDPBMdhFGqPYz/DKhmjgahHK9IiQGk1U8DfTDEyEDmvxsjbNTc/BEfWVxUM7rzzP5PkFALcUVLPxKhIunTtLxIo1Ex5hJm8KRBjs1yLP+WKuFBoBvNQpzzDZ+tQCT+oSbeB5/N4dxQM1J5zs7j32g/2bIzX4+axy5m4JvzzZe61qi2I33AgSDkJYicM4rjCgYaXKb7V//8o5ziW3pJRnYEBaFMkG1VrXgbHhmJLbchJ8AVN386QnnhqNg3k9Lof7y9xCWl9aIqCYUlPsTEkBnmVPXv4gov4uTjGkeqlOJSpNPoCMcMOs1h+2jYaJMLGnqPQhICbFGTRt+iOO2kbq0vUoEULrwIMDPhcu+6BoOpq4MS50vZrA8pizQhfVcntKtafRY3RDUjXpefu/tdLZz16S1A5DsUIq5DcmG45NXO/cY5LZxaNy5fP3yaVI4CNLAdMq0WU5EyVx9yEuYhZsgZ0dZFv8t1ptQXb2H89E2kW+RitjJPrQ6IRXLYM4C7+Rv7jPjw8WT/5wGHiH3ErWi+mUI7HlUv/d/ZgJ84hcZFTaAPt//s1XPxMqU8qOqS9RhlTIKELb4sNM+PJRrxK/c3r9B4ruFdI0mHgbbujfj/JwHfOHy767DywnkwF6YP3SMEZuDRJRNME9J86HbwhZHkLTykWsCq/s0/Iem8H/v3bE+xAKo8QyGBLRYDRweAQ+jb0lwkz0L0u8Ufurn
    username: AgCI9PHn87yC2q0UEX1t/1dz4U5vU32PtihekRwQj7779LG4v2o5ZY6mbRkY1AEykOqU01pOsrMe7ChzLVPHswcCJsRgAb7QaRv/3mZm1RYIeI5RPSHJKCHA8ZjOQaZ34sdozXC+3CPBiBUqYh5Qj6RlsxU7NDWUZKVrkqQJBXxptoVHXjDF/BlpOhDitP5lbLbMCJEYRJGs7UP3q6d4SNOVDSyVQ2fhGPBBIWqOBep4uR0zbsj5qOgT2lqmBDkYKY/VT8ds08OxY3XGgGRSWRDuo04qPrGr6Ip5Qy8JxYw4+875/FNM0l+Kmc61w/mH5zuWcVYsaMTh+D3A5dfZEOeWd3TORCiXuDpWCOw/H6Nf730AkJKa0HuD9+Lpru+kpELcn1tALwFakwGnSZX4hsUlQOpJJVqm1G8P8HNbXePbkQEmAap19odK1DofApKfTzjs+Bw1exhcuoNhDj/VwhGQzvLe4uJPNFLMcPH6WPHoIsYGTuztABNC0uizT5h+hjk9SCIER5PojXfM8dds+Xm1+7fSCLFqwGG4ky3bh/dEGtDS0SdwtgfU9aHSNYvJN4YC8DEq3ovlsWoo6ghmxTqXpMV5cZQ/MAR/oEpx7ctLsYGXKtyM78RiH37rel2KWmORgbm7uE24O9L73l8IQkW4pYeEB/LWmIt/DxyNLHIH+1TeC6Nko06Mq1uD5bO1vthdRkDDnJOt+h4=
  template:
    metadata:
      name: authentik-pg-creds
      namespace: apps
