---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: chemistart-pg-creds
  namespace: apps
spec:
  encryptedData:
    password: AgBlFpRMiYCCKs1sFnC1VdMzprCpbv3ReHuTzT8XIPLDmgadAOAFvVe6FpI30+tyTX2XxWxlwITjQWvw9/80MLNvEKMsPSiwiyzMaSXEcxFQTwba8mtDAZa+UMtJQN3wC/pJS84IyISlEW/6BpbqxzKIgA8ut/OIe85Q25g8ZcdJEldwK1UKhCzpbV+5YF3YMdBU+ADcThtzdRQBKZCUQFs791GErzLmKu9gMWvVn1Fg3rpBNSZgkei0UWwhQTQVP4p6pCn+LAzIVq3+WqHH9brQDOl9tt1HggN7Tc6udiI24wuWjRtKO4cTAkCRWJrgf6D0Orkn4UPOvb1Tta3tVRUzUPYvEoIGgutqA9yqp9FL/C0BvcnWluhNOn5YHUfZ+P/RDrEZwZRXKaV/2JE1eLJwL5ebhqqbka6mE4nBDn/JYExrIk/CqZQLzsh3QKbQ1d7StI9BqjvkIrhfbzbkvC4bB+QPlCSFjyWSMWzjiM0W5o6kdhSrajh56XH1MY9eGkvl8HntFmFL/bIQ3Q6mdLP4TA3gRoaLnwM9Zc7e60vDAonShJS7iawiSA3x2SajAg7usNfMsCHss1yI1OUUidKvCSuRXCLyn1Sa6Hu0zjPmPGb2pX05eaDqqHXFAeAmmz49G6lbWzAeP8cDZmGVY8qxf18UZlr5KsoHYXE3OVUvR7KQ2wWe0azHO7M/f93WrhipqONoXpu0oyKOwnEbzVBycw+vHCF7+hzkjuIOEqYV5MaSx2bcKXMHHXE=
    username: AgBCKgtmBz+C2C8aMMYJPz7kRRb+9wSxercRd1mxtEXehBrRLzSqRCQOehn1aerA83/+SxpIY++fvUPaFScPCDN0bes18YFtvuPzrmK4jpWjdwKcGx8B5OP5z5eKpqRe3dsNaQyjyRdtNmZZufDKezo8fNdYg5Sb7vXdQEDNuNMN5uwD8gNVd22TaXkI1zOOxRYC1IsdsClR1e6VupvGnxVo9gtYZULihBleqSR1HZz2mFv5Vj0dMqlQL4th/4Shl2CncXL1tRRsEqLXlRNALDNodlsuHRlSiR2Ku+7ZkiAqTjzK+HRaBa6JMStGU1r7+ZzIQDnXgAweYHzZQLlgHYfEpygVEmLFN+Vil4oFPtMBAcLl6LPATKRlXzFFV9yFNqVdM0wKAkE1JN42yagLBuQpgNa35UpzmZenlLdL04H7KA7ECbHoBSl0UbDZocrCRlwevh7wcpHIRVtUV+RgUI7Y2wdOkZwIPpP3lK8v0R4Lt04++pN4U6RvMr9NlSNL14GndN5/H/DyMlIUCoooqF3TB2fGO0dkDlkfqAnhbkegEXxSIeR12tk8xAXt8VuGA6Y/OI0UQ6hY8Oz9qKsvqA5G5Z2ZVq5DxbHADz090/oHvi9cpj9I9P7WVPLnXDo0FCJSqYzHtrDEmceewilc1S1AwK/0OT9i8Z/qCApfj1NO5cJhFPePCJr7mliH2CugJFWD9PPkWEInQpHT
  template:
    metadata:
      name: chemistart-pg-creds
      namespace: apps
