---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloud-dbeaver-pg-creds
  namespace: apps
spec:
  encryptedData:
    password: AgAkdLmV/IFb/c8r4+6nBCqlVEef6ZK4ppspbnLUX2ExBgkB4o1W7hN/LYqH16jCLKRcapFAISzBQIDwiZJhYd1hgf5XDhNN4jA3CMXDFpERj9V6TfPiumkF3ikVqknIMCHBlbnReqMMmxp26SDZJAMkw8n4QevOcXdOtGvnLZa3a3Z17EhHlcYbpxaVjNkEWbgiU0tMTg6KmCUxokNeSAJ2/pUCrOun1jX4MDIu7ssayCZCT/y+2izH766DxtFRLXniV0aoyHge3P4SbqXUA6wfO1ywuaStWNK3nMNMj3XUL8mxCXv85EksNxpTHATjrrDKDEiMZVwlMDFIAHH72jN9MsW+CtWX05aoincOBRqJpTCu80ISNdVM5RMiHQjOy+FuSkLfIMbj8R/P8iax49WfPHljk/UV0/G/7AIPfkK2Azn/pZ0SrJ58dw8LjlMyZB/dyIvPp/XG7kxpuXiZDXtcaOktzt8b1wodRJq93mpO42wb3Ij3HnP7OC8CjNT50u9nIYSgOGThVNlmxlJdNmrC11wxaFBW7jktEMDh3sw7/s1su4AzkGz47t+G6WmBLu/z4nMTtMOUznEYZnCiGJ83CFuAeYG4py1SexfiY74+WM+NiLJgOBNbptO5h/6xfgm2NPHXodagaE908F/8P1wbeb4M23+Jh3/kstAEnEJPO+QhhdTQY2OIotBcvc6mR+OvP1Y50UsxcN2uc8BWM863y8+bHts3qDGq0LRyircIXJY5c9pAcXLhxox4
    username: AgBuuXxMdITz/ppeH0P58yMiCNQg/kPX46ymK8tG6bqCvL4l7uULy0GjNRWuX7h/5mLK54V9hqQKybpS0WX8c0DFggSk+HH8xQWsbrOSBdcZVRM/ak8qIWsgCD9LclQKjURIde8uGAKgc6XQegbwePjVsnoYt6oylEJHAMmRbjcPT5FmQCq/rSQig+PyKJaG2XyThUVJ5IPG9WTdn5A22ZT8qb7CKnpgeb1lgJydgnbf9EpbUwunYUrozcKcaVcQ4Dy4L8SAetobL1P2CCHXGy2iws+eEpduIXdq4S7SJ/Q+VZS8c/rcxaxhzX2lnVmMbghwqzY898z00zV1Ig8iFScNgy2lnQyImjt/WMamutQTzVcnKorLFtyCBPD2kUWErsZZAJ/+q7c2EZnbZoBTw5j377w9wckOHHaDR4lR8Krz6deWfMUVYDt7cwEF7klh6NGBYVFuXzuvozI9BUShBYGcCbHHybX+5LddFsOpc8c1u0LRDvURCllYz2zUIt7bEJOwcxq0Fkf9n1GNjnLtiK0ZCNUaLebcRxXnyNuPtdj/7xxzglTLJxdDIa4pafEY5LJudPgVNgnqwbx+C5NKJpJjc823SUz5HCCvqhWCtBA2Ulu9hxEXcZWGrIuNx2jUGdalTQlxya/rFpDdaLdmTX6B/SQxQko93lw1+q1WTldIQBMhemx3dXmtUmfeLYWr0sAFvO2DWv0EePtN08Pi
  template:
    metadata:
      name: cloud-dbeaver-pg-creds
      namespace: apps
