---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: fider-pg-creds
  namespace: apps
spec:
  encryptedData:
    password: AgCQLu6YfiblJiFwARCdzWevokZCNfJHzE4OQsNKPuDl/fdhKj26q8tFnq2lfJJT7KmB6jnxMVUFmgwPISSeTUpYAmnIGEpQFKa1DfC9dbD5V/49i7KdknTfjvFfADB5td08qRP4trR8dC1IgWu6vwsg7mPAQFl/UMGMEvY0Gz8TNUKzQ4ia5u8OV9bHNbhHUkcfvyBFfC7FDEd80i0KqHQuaR8E4LEgtdBBF2xHX+UQErba4eg2Ht/8HilmzB39YYNUMKmR3sO42h02qxyYKXKqklYqPENWRmQsPNypFm2d1SyT5Kg/87aI7kUCdI21LVZHrZCk/ZwFePQZh3sFEx8+L1Qgh/7+KqxnMsjCozHt2H1ve+jgE46op38k6c5oniViuy/19pMRlKQUJgO2VecGkGzJ0772/lwsQF7L9PULsR9tHtA2sr8Ym7UO6nqRHpgT7kvk0Q5Ksfs0PzFspFml97OHSPx/jL456i9YsCtzZdgqjcgQdYW80fiSKBNBw+Gv97k4Q8NQTCtxGQX5BYBjSpcgMGENlA4BTCiogIe+xkyJS6qmagUgkjhsA1hwS9oAi11s99jCD6h8G5HKzyQPoldYpa18GfJcUFp/rugni6I9JyiFCxfSiToxZ/qXBYVDsqZL+MuQUoAh3oMax+ajuv7bJthPbwIa06OiN0JstOKuvAqIuAf2sLyRAI8hJpXzGCUV0xaYfwtQ2U/I09550qtAsIENoaW6Q4Mhh7oAEQ==
    username: AgBfqCCCamMonxgZuODaPgxlnv9L3C+h97z8qyfRwVFasqme+sdI7XNpx5fYU+Qghw37Ly8Biy3DYRCIPCSC5jNG/cu7Y7xhsXaviy6popZnXMLQS6RnPQHi/V8FSuQvsdRYzjiT+PO+p0dSsJ16juFBoYBL1H+RtSRILRdGJzwubkQ2tDOSVjygHWMEJ1gqR3VLTfOFYnhNtByejegWJ5o5ul1nUQVjPFiWQpczIwg1jHVr9rnodccPgdePuIzWRnX7jmbvS0jeG6R/mznsgGBtpe3tLabARgvVyJIWHz+q5xaMPkMfsW9gqTyYp75CfOMLYVve6I43VDSz+R3IXPvxJjpsWGkDp7E7YYHu6OwFz23GGE5sO9k0Ne3toSm/TTQW8VN9cCmhkjEpGjwww2sB0oAY/z0UNDRjsGcR6SzC9fl/2sNuiSDlC17yMoze+HhVeGlMXOUF+IE06TFIhbr6jRCzc01lgQaJZEJgcFKISIE8jJisQw9AMV375FFO/5bvMUqVBBpn+NcW034jiCLHtsffqM/a6RTrsuP13mSvum9SGpLTHHYazPSuqoJxReOa2LMG8RdwmLQdHrD/b9hhfEbmozzQAmDz+I4JT+ghwpI+UW9T8xSfZ1e4gosJXjdMLBMuOFDbJK2SQy9kQ2jQtcIxWFrzouB0YZeEid2UZ0DYS1gfLVwIXWdz4+OIXKgXJist9w==
  template:
    metadata:
      name: fider-pg-creds
      namespace: apps
    type: Opaque
