---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: guacamole-pg-creds
  namespace: apps
spec:
  encryptedData:
    password: AgBPZXviAVzDmEPHPAoQFOebC211uXDiT69uX6Rlg1Z9HmAy5gy2+CSJbTpYm8z4f7adIfYqZ4ASjr8OebwtlRoVmZhMqvsfHQ2bwlCPGUNtfDwXTlCNH2khQ81Ws5TOlQN0YpKtucGylVda1nGAga1MyX4ksobz5O2kYmrHQ9nhuMnRJpuZ5tVC/H8NrLI1DFMCXV4Lvazcb7NdL032gnhK/ecANnwiSk7uR8voNBTE1DVWpvu+mY8Rpdkfccc9M8YmoRKD8or/5H1kW+SFOp7Fq/zMSfxlvvPD5f5ilmhnyaNaUIuPvjrhk7HwL0A2Y/YZVXDcoOqKB17y+Gdl8nHS545uf+i99V9NYkjdWRhLRJUnm3JZTzIdArBJaWRV57NSOqH+4naLOsSRDZF4olxlnifnQx15bBWTt0/4UZOmZa3yDwpTVWSpHTh8R1t2KsOWjFNtrpP9VkDiLgcjiBDiXDriklN2JeZ1rEEkSZ0r8PI5wrClAAMqDejCKUba68Kw2xvW4dlwFAqBLCgXmq/gb0e7zdhb5jPnrVD9B2f7S5sw8KzmXPnUcJsCm+nRljv+Qc3McrjzzcqN3IvBHNshXLe6ohrtm99tfffpCzyAXYJiIe1eMADc3AfK4pjaWB7veAroI5QUGkOjPDEqQwk3CzuViQVsieHhuohQxcXm9Nwi/CGjWbk11uj3zPp9UI0TOuRCjigzQ5eosWuK1iVm1+Z/8j5tGztTCIWFJIQKvg==
    username: AgAzRlBS8hGTurnhlY2Ubk59UBsPNjH/nTU/6rpyzSb/QsWcX0VZ740nxp1WyQ+c5/O3mw1cXHAs67lIT06qb1x1FM1rtPNEo35gPfqdNcg2NmG+FaI5qC6Z2+Zpi0Ow74XWJOvjPSPrqD5+6Mhcla1gy4OQJx2LaEnfAt1lJfam0zQR+77ycCpnYO213Q5WJGXPWhwDbswlat3kLZimr7Sm75D6fVndeHNv66GQLuZz0mdAKXF21tkV9uaJU5PcubEF4PzDX+8sFT4CjGSROp5y9d905opwGApC0pnXBoB/m9GJrFpRc/KSWgiS5BavALCzYIR0AHM3X+Emorr7oL/rCIm6r757RrOEOvPi/hxaaZt84x4O053jNaziwcAmHt4vcVavUlsLG12Wfl5ojvV+zPH0FJJalr9Gw5tXzZ+axQ6cDjP+4Xm+kBRXXiYeLfiygHKS/R/7tA+2KTny1bcIvNGzoZmUIHPZTpYbLCfb9lFGasP/r4Ti/VEx36eqqeuX7H4CpkrKZpXjRSoh1KZDFEnG1asw/hVQaj+cbvnudNIrc95bmK/4PfWmeBKLrvuNsEzBSlcqjxus1ksNPKAvkl2HjU1j+Mc6UCwmW59E+8dgaDbbL9tkrMNXO1GdscnxW0OQvHUxI/zE2Iips//wDtOFFlOW/EE19XykNKGrg7Q986FQLbehewvBiQ6+cxcDwAN5kYFvJcI=
  template:
    metadata:
      name: guacamole-pg-creds
      namespace: apps
    type: Opaque
