---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: home-assistant-pg-creds
  namespace: apps
spec:
  encryptedData:
    password: AgBQI6KN9QB3HHJoQ8khOKg1rvGCLKCO1UENcqIbvN/bfirabfMYVUeXx9XxN6tjyqaLzBHxfXHolsmYGuvd0obbJwaFA9xP/BadTwdhjXExH1Y0KImDGtRZGPGady8SYWVq/UAoosCiWCz2ARG7OmSVwTbM/XiCREf9cG5CWKz74a2EJWLP/Q1Q//Xl2eQg2b6ObjSh4SZZ7diUdNxbe/uf4TMEXnoWE/mrn45vuEkNqdwYKx87e929H4rqDIMstec71p9H+2TCg+zmRH50CDdU64B4GsH5lJhJ8rzFbPD0SjIt9V8PR+kTF0Vf+KSHwYPMrbroIQAIEwl0ThrMyP472qrMhT+Klq0cwWe/th+7W9GY4fiGx3OLZupi1vr59MhicMc5mIhjQZlopXZzBrzxkDWV7oigCqlq+MpQHgSSLNo/h0lxTxL9G6Nq9lJXhbfP7NgFsivwLEjmLXsYt0M2J6qlHyJSvlx+c1E36HIgmDLpGNzdlWQZguaR+UXGQp5dhq9cmZ1esPlsMk6mv7km6aV/rPifgmAOUFR4dE3KGPwenyd26YIjI7zlkdNoEpLOS5xh+cZOoUTBgQb86GlIphBCVvYX7pb3bBhCzuP8yygv4az99n5SeF06dUyw665OErS4VGrBS/y16HCRos3GfOnxl9iqApv5pgfwKtaUXD6EIRzddS6x4nmPXA3SV6N/VRYD5NEqhm4blGYiF+vTs3Z7RngHPB6iKmDqoJM2CcibCGUDifc+YGA=
    username: AgAYeFChyQJlUQ0KPN0c4q9r/PtNBErqQ6D4kYLKBxQoUdG2Qg99ABJ1DwSXb80x/ewot7loqSW/zBXmBQjVvQkR1v1O3LKP5xHSs2wyjX5E0fwNX/70mFXIV+YD45conMGN4/jV0vZkhdfgZAu/BWJfRQ28mr19vLi+OGXHavTDS1tAmNgXKg0/JBFW9Ru8OD3HO+nJlDDpvSFUIyH5VDP85540tAtjJzdsT2G+bt7wmfoD0izWBAZmN9xo4vl1AckFR8/ddz8fQUmmuL2ztsAy9dc7pJG9tZoJwpIYse53ARuZYGEXuZfAkb7/J4kCK3DskXvY/58fO6yFflwLR7IjHnF9rCcKBaocjEpQNw4YYyOXJQgZMo17hIGfrVsuTQeeLuRPdnw6UQhRaZYIaqGd+cTD3LWpMVQkwUK8FqOGIFQfKdojb9A68EdWogdMcArORhJT5BF2mec2G3JwLXCtShEluynTjOiHwgOS2Cx6naJl2aqtIJUbN8XRau9L99jNFwa2rl5mE0u12dAupcNoeSBm677zwfBHtrVBEDP+lm0ED17ZJwO1uvQfx6m2zJ0bOYac6zWnorRyBEgag2H7ISlTgfXrvpdL4GKda8uOWxAQxz5K7OGkG8zCGnX4/KtCo4q/jhaiKPjqvXu3CGoW5yHa9R3NeAVF9W+IDsbCUnkk2J4lkB2GcCFvJN9lQ/zcJumCPZPBsIE7EkJ+
  template:
    metadata:
      name: home-assistant-pg-creds
      namespace: apps
