---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: jellycleaner-pg-creds
  namespace: apps
spec:
  encryptedData:
    password: AgBrZs/2LydHBEdn1Bo9CA/Ez8zBoxKGOonb/I/+sT8rSHdQXpTosEXDkpijWb2oWxo9Q8NZnC7TZr8ADmo8QYR+DHekMTf2KW54/Fq/SKJtXoTLhNyVhZ5wM179yGuG7a3v87ZtBubzlkAV4fhGGYA0t9YkYE+XNku5jr5DMMS/8+2+cnc7Pdp6LzSWZRX51m1Yp9RNleuzD9HsMpscNqFxfYMdtqXATWoaWXIVZPLVGFVobpnyYN0G0yXsqo8KL3Z3B0BqT76BbUgb84upMcVvo5acL3yHhMWRIuRhhVdE+6CiKwcnPH1lG+Ke4OlOyJyHUd52QgsK8pRBGehdhUiGsIpaGuNybpG//Jrq6BOK6vyA74Gr27Wf3x1jYtE2JbaWwRv0OAraUXG3wXz3/bu12lljXoNrwmhlPQezV9FL0qCJwQu6Dn0fGWujKjRG+SfaKoSzW7sEF3jriguDq4fOrZbB9Qm21JnHknAetQdTDX5H9wsqAgusH9QVGXNfJh6zBQ0yP1T1Ha2csFPITSaIRnJ3U0RxOYJ+LXfevYDNFyfPMUiA5MFvsqzgYAEmzfpwdECIa1IAeGnNYHQSuCapE7mWJqargEFNqasA9FGtV0vCNWGQOVb3zioL8KY/PjUQK9FUJG4wH/G33NcBjU/rFgyFKatAH75jvgGl+b+9DjIzDi7tar6DMJRp18X98E+12AgKBDZ25qvJ75Bonwv1Sqb9bUE5m94TWQfXUmJiOf4HgTAWnlZDPIx5
    username: AgA87UissoFXsEWu1RPy9l1Y3JZ7A6w8ET5ZEUeXFVAaMuXN0TzXX3GiWU5QLw8G2XEbBhVyBKr5vGw/yLLSO+c+ZWYWw96VDLn8wzOxvWPuMdunSBYahzPk31Tww9VocraSC9CajdBRkajbKsY/ddwHWo+jD+7bxLaf3wGJ331ux37xIglrFIFEDIaNHebsWUyYJEgsSrlxw07UiC2B9LxAZuS6cqcsTooTOMgO4RlWP71rJvQS19msTCCzI5ULePgWdnY3sHyafFzBdZ/rzrDfDNGKRSyxcWndYyR5LcCIesR9s4yZzqUwdot/wfCLVp+8wMGfxxC5S4YzdRjum92ZWwXSv4MLyBSn45XvgVRagQ3BLa0BKW95JGRBZOOS9lPGSZapX7iRuoovMWRXgTqVkJxuwJ/lgLY0kbgFPSFO8IkihnZuq+v+0ZuxxgUf4Joo1eQD7ZDvTpq2qeoAeUcPIOyaszkcsFIjExXaCApnoQNXLpZUEZRtT9JI7mSyMeS+fPe+LBN3bCYpKFYPvUM30ugHXf/zADzWTwoSpJMLJz+Pv2Q/WQKbpHzuc4ZRqpqBEYeEtHhL5saJZ2kDdpBgI+mVX5UQm1dQdun4BZXT1tLQ1N1eiLOpsIYBfSiFHXEl+7uhD2L437Yi/BE12PP6/x49i7+EQwNYsvpiJKhjjxbg+AonamQTAGF6LGE2aQuRdhf6v0aFNTRAjeM=
  template:
    metadata:
      name: jellycleaner-pg-creds
      namespace: apps
