resources:
  - postgres-secret-sealed.yaml
  - apps-pg-minio-secret-sealed.yaml
  - nextcloud-pg-creds-sealed.yaml
  - authentik-pg-creds-sealed.yaml
  - paperless-pg-creds-sealed.yaml
  - mailu-pg-creds-sealed.yaml
  - roundcube-pg-creds-sealed.yaml
  - airtrail-pg-creds-sealed.yaml
  - cloud-dbeaver-pg-creds-sealed.yaml
  - outline-pg-creds-sealed.yaml
  - jellycleaner-pg-creds-sealed.yaml
