---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: lab-staging-pg-creds
  namespace: apps
spec:
  encryptedData:
    password: AgCDLpdo6Rxp17WFBrZ5tlNBJjWa47HK+VL4SZZFDZXxz7c9dT2mGRy5Kpzr5I4ZYb7ES8q+r3UVuhFwDMc/9+odLwShu8dNXj5vdZndwSqZnLIMH/oLYJ0FgLnNW083gRr/VoThx1ZeyChs2oOq2AZX0jj7aXuBjuGVLhc+J3xrvAaD5c7jIhPvk+vzZnfj3hB86bbo7QcdmLFobprlZFVNY0rXOzpsQwuMp0BRW4ONO/SVzqOGTWNh01NYGYL9TviEi8KAUkTc/CU20CErKFCNtSjl20SL+cmYaprHyb4JwlH554eTBKpybo9/TLcWwVfSJj+70xKOVqzcuXAN1CNxm76PAINb76MlVAkrkfsj4lqbfBvK1n3FEG364CBskwlJvoEfLbnvco1ZHHeQjmW8yNaMgmBv1XpWsOEwsrLaETKQPcTCSZqesoGZMzF4hNCL5LpjvS4vJPQEwI6nQ0sNxx3uK1GVPb4Opz0eFdCrsRyPVE32UndvS+jzrr4ABrbE5MOo5eglhxDH0tSHrUpbMM+9PZyoIMcJG6ECiefb01+ShsjXmS5l1Sei8q20o/OS/QtgfLMLA/ZccI5OvQgTnESjFmD0914ScoFbERL2ITLYx1koD7kUBRsKqXES2WR+qGkXLzBZFY/9HXDL4dC3eXT9Fhis+tpaI28QZKqroNg7p1eZjuzGIeK+skZ7Ic2uO8OZXbWNqrlGhigSHUj+9Q+R/ijKMtU+2Crwk84Scw==
    username: AgCGCG4l2Usfcgb/BsTK7k1ZVvy1ESJb3LFb/kjStzZiJLgTNoFALvJhcJiFlpbZHhTauCZ6/ndIerv/lpWgzubHv2+xnERmm2wccKOtNRv6v4QZyS8zAXHfj1+iCIXmJuvVm/MClndBux/zuwYVIjDwj7HS16G8e3XRYBvYajnX4YD9RniG/Y1DEETMLUX9IctNIuW53SmHzj013Bs6u6/7QuzIzztugfIsanI7q4XQ0QpMgiSUCuKs7PlvhYfrW7h3tXWHM6RCX4ckqTgY7GRw8VVe7F2i88rBvJYuMiS9vCnMpCTLc3rpczuhHaexpbj3tAi9gz/q+TM6+CbTVB3WVQGYUYSyOwt+b6tu85sb9zAV62iUySgFMzRuDqOoO/+a2Ij9AYE3WUHJs0SPPvEDnIeVbqp7FvQUOobqmd4Bv+qpIIpDWm+2J5N9Rmzjs33S/xxhiozCkBgbglH6eDMRUevLLtdibJFMazSFts+HpkNWYKgTizte45qdKbh5XBYuXjBg4+3CHOWDgXNUIDJREYqpM8R6ZyiAV2ou4ndH4a/SA7yGW2n1tVlwJDfjz4/nF9IPY1B8kZywTy5jIpkOdJXbqc/U893dPRXdaZtRU3HShMjghU8P/WK1gJn+MNuKIloVYObZJ75ezO9w9XzWA6l/4jGG2tnN9QKyDrcoFjMveRCMECz7pNryvk1lirSf3f2xbYAzJoppnQ==
  template:
    metadata:
      name: lab-staging-pg-creds
      namespace: apps
    type: Opaque
