---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mailu-pg-creds
  namespace: apps
spec:
  encryptedData:
    password: AgBolAqeakXAF+iW4DLB/8k7haVSjLBlGQGVpA0uvpMkdpf9XKweCnmPpX7FQBc45Kwww45eZ8ml7/x+eWP9rFhP+1HTalV/nrmpN7dn85ae8gPyxGIyqAlGY44jRY+Wf3BM3RXfbAE1F6k/CH/aS7ktvnZ8Tjk4juAWOm7vsPINvNbkyzr5VDvbu5hHf8SDgNKsnj9jSB8irFagyteqjJ9PQOUiHKEu0PpCCotCLrgYDDkV9coAeptz4wnt/g/QxJ5yyCRAxTZBGM9OgSMrnIauVKOq5IbmXNpIueoULnwpKKic527gOYDazZmFGnXgaHprgkdBAtmS282M03kBJKtygtjucnX/LEQ6ClBCHWUj82wEDTXhcrsUHnVGqjaZWZz5qNFKTVWokQz+pU1rQgCoF6WW8gqPkdH7Rj4YVHdf4iYAF+/O/GWeYu8rqrPiytAYAcvTA7dPzXznV1VpS1Q+dI8Me9q/r6GENGAubUqCn/8xIibh5NdwqEKuIplvf5oHqW4ESXN3jYbHl/etQWyULG1mVPAb+gcbYu8CPhNacr8EqcaId1i4bYDUe0D4QXiUgXrFNry78K6s2PKhNEJOYuh7q543N0s4VSUWykeLUV1HZ4VzRhjSj+UClY0hzw46ohs4sE6oT36V40WgEO84z5qiX4i8a9vUmjYn18NLOa2JNJnio9/4QD8iYm/uZ0uB2SH7ttlWWBKLbHHkk3S3lJrhdaxlktwV+4XlZtXneexvsEf4d8fsVw==
    username: AgBo1fviGvCCQrYPCW/AwPj7ACGb/aratCVeEktH5dGhBS0blemdKQmthNNO0JeAT4DzBATpBTPVDA7IiPqRSNfskT6iF8LS/iZgtexhUal22jDcbQQkoXJjlOv6Ks+QeEj+K2etXQwAVw8OMSnqwDw1HD/usFu2P28dPkJtULvPRkonLX21Y7d4+jpK5CZ04Qm21pAIxTo050SkSs89bsDZjwUcxuYJvvwymx1M66kGirEUBdNNE5vWWEpZt7wUb88mIPUiK02i1kwWD7FxmfC4M16DtzNhrSDL3ak9BjP4Q9Bp4l+5k+uZwqeOWs4jSjVAewg6A8GRoBhVVqgrEoek9fHKcA3xlTIvSN8W30vDsGSPhulYQJ9NDmOeypDf9Qu/akCQw48z/TShby507bSXKZyfpiZwS1XGJDEJAV62LvTlTXQ/Ij4KuMigiYG95P6SVv24Mhd35mjrZ/LIe3UAi/BgYU0taVT1xnjFgbkyiuPvQI0uKhc0eiXIzhUzamcc8yRDqKlFjsfKCz7EqwNw/UIjsK09ZIlDS/7kCQEoSwkk9YeCkFcdlAlrWKzGPfpMK4SqvsGgSiOTyAX8OBORdCgRQUilCx78ODAGm+82xcXm7OrvpiRiMmDgBwe7L5xQh3j0UkvNIboeLFan+HoWjPn5mGExueDU9p4xdzEYHvs31HJQe5nW8GrqXi27R9XScyTL5w==
  template:
    metadata:
      name: mailu-pg-creds
      namespace: apps
