---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: memos-pg-creds
  namespace: apps
spec:
  encryptedData:
    password: AgATdvfgdkHTr749yx7ffEaorNXeWQD4DfWLBN+QXx9z2KvAIlDX1tLxlbcc0TLyyoGBY3QLde01s+K/CyWmZ+x5acEr2D+apawdxusY8jri5hcTFKTSMeDPmBwC2xQnOo2vs5Yl3SCaCUMszmETik6DP8vG+Xd7XF66EiOIsS2pxtEH+yA+Eh/x5jJxE777d6axqF1gNkeNXKBrwKu5vMLLJ1IcZ2TaAtfjUE0Y3sCzNRx8RS5eGAiiCi3ftLm+q0H0JDQI6u62goLeV34GiKH3x5H8f9FHoGvQ3hiOKjN4CT7UXL8yXsxfThKTflMoOf7iezFPbYI0OSW1rFoOIChO3HMtE0xiAE3a9HwcPaJ763uEWq434z0KnHhqluvVvGHYUtD+eb/ULDsS/oT9TCWiPZ8CUo2A2mnoMU8KA4y/zm9KruPR1wmlAVci7Exw/LZ7BvUsbwUoN9LuHGh38xC1O2J+XC2bNw7DDah35qcAg3oiLwEuBJmSg4NU5lIoQKTbQID5iUJhSwl11OO3wFoAbL5+c3n6+UT7j6hodylNOQ6+kYjCrP6qLZUCC97EcUBfL7uqjoOpnUKplpFiuNGH1Za5bBUO/rnKKOId/2L4IPK3H/1z6fOtgMp7hO2sfkNM0zC2XnHkScVdgpDVusD8YaSpTV7b/WqVLRjfMgkQglUbQlGIp1bZ2qoIAzIR/wjXMRwddh3A9egjZz5gF/uY0C7ZN9nvcaMtk4bSUOuY5w==
    username: AgBR1PBNmbgce1tIEemzKm/7MNuDlIlVUguNxcSeIpsqoLN2N1EbPHz5MWuMwI8o/qj/g7HAW8dinYDCFiylD59xnA58IUKT22+0T6FW38XwMQ/cq1UdIdmNRlFbpureArNj51B/nvsoYn4tkQ86hiIiMbEctPebB8oFVLXkr/8V5iDRFLXfmXXpxoqhys8FZoYKxMDls/0W7hs/Pkpyk0/yTHBpPFvHWkO8b2dwhxagO91HGmOqfzuzfYwoxCq5so3ZZ+oVBVm29RpHXUYOr8busSZ68CSkxNi9pridHW0VFczNeGpQpbJAYr81iVezqOnlIEz+5rNQrsM1Nr+PDpWkV+5LZLTiUCIVDrpipffSzopny2I2hPdSQDPlrm6hD7hV1wNhlUC4yrTpIj/i7ThnjMWmCUKk3vqguZ2Abz1/rrsHZwc0x6YrdPFVj3znHQgTdB1F151JZDA+Aw5PjjykRtXPsYRWN5zBzlTXWWQdkvFaUXUkCFhjRmXVRxitoKyUVcYctSpF+1pOxthZacAFY6DwoEF3JblzzPmqDQLM4sceqRk4ElUJtxnqEi32vtbwwCeEuhcNrhjvJ0OFEoFTZc1lql+cbtZCMcQcFvwPttcfHXWPJ8mgfoLS/eY3fTT/ditAM1YUFDgC5X0xv/qoB/L6GQHyKPjszmQRrmFDxkWc3zY/IgKQB4vtHx41lIGhl6uwzw==
  template:
    metadata:
      name: memos-pg-creds
      namespace: apps
    type: Opaque
