---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: nextcloud-pg-creds
  namespace: apps
spec:
  encryptedData:
    password: AgA5cVmzRV/f2gGPnkrTYpIseBY1yiQNiBmd3N+doe/jNZAs4Ts+xmwHw4VrJ4OZsR5FmWl2ogbnd1JGsAodwZDmRIWP2WhWP5csMC5BUuv59Ybh0VRNv7eyqng+dDdCXigOigDUI2JYMw4MgBEZDyCdmw64ZYIJFyIFqeBCQwho8g7tbUtjXJQn1toIjzvj+S4+uB4RAvBBlOW1ElRXUZewKJ5i3q0ATwmf2NjOIDqC1BWHISH/LaevlI98MY90RMcScSA3HMljgz0K9bu4ZqBI47pXKUb6bHW/MfjPFMwgCO0UWWnW2RWn/k5NXoXyqwlfUx2W4RhwBVGwso+/EumWFND4kAm91FqsttDjdu20UB5MTNsFiGAhnw4O0MDQYA3/2+C3s6qYtQDvaZqJa2czEdUYNI2DIQmjpLzMG1JiLClI272+yixpGQdcheETezVgUgb+5KmEhZ2SE+A5I8Bhb0UUeE2jjdvlTu9ztIBnQ8jt3zBf/rTVkH9UggS4tSFhsLIabCOrv9unVmQmTNLJ3dA1Ba/KvgeIEMm+Rq3cD9aNSarRcyDtnJL5IUkKh3bc1bGI1mXqy5z8MPGwFyiPW/AvVetnDuFr8GaAraBI76H477r1tA1Flf3ZkK4cYlVzBAhLxSg+3sSDDaemZLi1p61kwQ3ahG4iTuCnkL4c/Fcf5BeNM3VCD4uwa1JZhs2IeaowkQdIt3Nqafm7kwICXtmBc3LCtOfESyXqr+XOTg6TVJwJbzffuVs=
    username: AgB2rHVJUgvmhANvk37mVzDayZ4HF6+KkeP8622aMqYdduHi2zJC5vr3/ufs4xikoRV/Q1La6yNtz7LwFUul2tryUmItciiOA7D82glnDsJDJJdkQvbd1wvDwGuFqbreCYBLolK5N/vEgYME3pqNzpNRzfljrrVg0qnYSayv/PioDpCPqZcUXcqVrIhM/FWiDJMSrLdTRy11YKDl70ed6viUU8O5O5FrkKEJhlkUY/cXZGXFBzDUb9ik/MofAqgZ5idc/nCLxBqoDYI9M+klSDRa303fXneTVStOPgj9OJp0tilH6vB4H0haYyzxF4aNRkModLCT9WOK4cV1GCbd1VdQWfdwaOEzdCNt8/piwo9zn4xvDnc0PoKLI0BuFt9l8itxNSIFy9nlWjbPfuFh/0qazWuJOW8Q5DYGHF2z8+RwxNyIT1uD/k4vYGmqErhuAqwfHjZei5kfHDQyCSuFOkcTgdUxP2KZCEXWdS+4H74sAGuGlAViEcyI1uVx4MbMVNSiJs1jN1HmVl3nnnUEku3yy/Heda59bmETyxy8O108bVKd1VBo2HU/WqlyxzW/sQKnK1Vo1UYe+X/21P0Ilz1xc+TceQ8BJNx9sF48WD51bmDsr4J/lYqgsIz5A8s6WDNDbzbC9XFDONWO4+nDBF4pBJKnQmjAEroLoIhmtIPijYdRjo/VyTJleLWgkKK1b5nu/pLY8+FRTtk=
  template:
    metadata:
      name: nextcloud-pg-creds
      namespace: apps
