---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: outline-pg-creds
  namespace: apps
spec:
  encryptedData:
    password: AgAAQiBuglXtJ4WUQTV67NcHhj10i1yi0RzK9ReGdYosJqJErjITCqca5qezmFD/Bw/ZeVYh2W4VZPFEX2ZNoy7qUZd/EBbYqmxbaKg5x+7GCo1gWfhZe8DQU57SyVLUpXYSNvp0mMJej7viSbmQRVTE/hkCSNztmgf4JfSlI4llGHGh4JgpbxNY9XkUK4QjFW6WPfUPW0bHceZHUiD3Urry+8SwYcW4Z33I2pPuwNpaPnLom7PnpgOi0RHoR0akGPGEEOh3RIrGNTXvIcx1kcY5QzayndFyVMuGTWplJyuNr2o4CaYWBUiHXpwoeQnUNZmmXqsH0RPDkbEXA5t+DPN5CeD5QS7busL0//YDrZan84RGRBkmvVhEFgSoLp4a1uvGuLrPKeEeEdMBgjTPDVHQw1saTDPHhN+eH0wctrZ1E+jN6pH/lR5kpwiyB0Hs2RcQr65JeTbMVK2I0YyHmXVfwIoCC5q4ja1E6/02R4L2MuKXTvyGRlafGwOnlaTsU0ypRl5h3s2evyf1QiUEQyb1Wvw6Yw+Ph4Pfr/Ra9q0j6oN8FxM0ScgkAv8c+SnK3nVIH3x9MG7WUQYzMk3aeKNHAY2QCLlaJXWiq4ph/HeKbZErP0RMIgY8gbhsXIrAiQ+sVUntPa1ECwWZEpCLz//CCan5RNi2dPy5Bq56k8+Ape0IOKwldUREKk8sEByl4G3Dfrx2LuC/kePGpNvXiAXKAzSfsp/yWqEEHe5mrfyDuSw+DrRlH+ttqA==
    username: AgCljB/m06hWzp7/G0bN14FdmKr3SNCtWTgA3guoB+qxExOoPvUlF6Dc6+neS0cnUizmjsvC2AtfE0Zg9585hh8PqvjTUbaZyVXzsgJMDWLvi4USY6z3Bd0WDoAQsgbsQKdJFi1lVEc3BMLrkZIrNE+PusE9th/ygjHjdfqdq7022gil2EpZ0TNLC/u9o057OF1ERjqzy0ZZMChyaPvNmnvHTvY3mc5+Sn4y1bVn8dvyTCK45pY83aVJ4fgAx7Bh7u8FqSKOZywRgy3WimtVwF4Ss8Ee1FKcLghpqO61BJlztXjbIwWIDe2jsoXHhDuCA6UC1XM9B7RpdQvh3SwiM9gOPsJ3Dq+KS296bVBJZa5Ucl7H4dyj/ZIJliMNCDpi5kOXsuAJL8Xp2ubCOif3sDotCdRLYSX/Yah2IJkm7wBDO0cU4IIkVrDf/WVVKUvSfAhGqp5KkiKn7nkfpVffcMIlDGmBOC3xRL2bpP508tNvuR8m0cRHhOK4J7Fouy8s/xPA4neOVQfyXlZZXjWZSYgAJk8HAE5ypCE/3Oo4QZ7Y86dk5xKmMYfHT9yJHMP/Hsv642+RRv8bnlbuueYb5k2kp6OC12zKUZaQH18uTDssSldPYqx+txR37/uaF5EombrE48Kj2p+/wYpFFnwnfEdhevcmm0d2YSM9rSuy6FJ7Trnl89mYm3QpurJZbuWr7tCmhGTQjJv5
  template:
    metadata:
      name: outline-pg-creds
      namespace: apps
