---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: paperless-pg-creds
  namespace: apps
spec:
  encryptedData:
    password: AgCwsKoR60OLtG1pzqOYh+miLsobUy4mwat8c3pQlSg32zdIxo0KamJjWmzHZii0Lka44zJ1z3eTl8nJP4Xln88cbNeSNSWz+RBAtNn2smgdcjbgayLj+ymRZzxrK0I6HnHgKQL8eOBb8wON+cunRCHet+RnYGv+EoI4Yynu9MfY6hxrbRIcGA9uSmSO7Od0zPom88YLxrt4mCOB+Gz+icKEWt1hk2TY0NF8zYV+pIp4/9h7QNoBizEngMrXwKgP/oQ0cdSV76gIq5CdT3Dr33NEqo0eWX5/cMnDfTz7BylbPFfxjd1eWhWQD8YCCzpePe/myrZq8LEw+V+D1luWiULTFa+1s/iHzA4i85DqWKBt29DMy8X/V89uCAWUsgQChMpWozSb+PIFXwrchFIs7tAspx38YPlnDxzQ9GUPfqk4/pYItVLD1aVEBA5VlduO+W5hsc3jyR8iI5aBfhYuqRflYBHzppOFSwVVppUzO1OqUpkV+M6LxM/xyuWGZ0LCppsSdmTbQnn6WdmJUA2tO3zjHwI9a2S0P5dlYMyMvOWyCXiaxby4YqxjrR9bp6tFULYQs/TcgtcgyX9rpdKaxVLqj4Fc648yYkKHe+jDy4GZPbrKus05U8nhUmec7wba5N4fJ5L9HppSftt18RqBnlUlt3/S+HAijtYe6vB3RB90NaLS+t9yih12s8z8s8Ote+3Hpdvqlcf3APRLsCG9eeMeTR1/bhoedvaZExPrw2YyIdQhPeogxTTCwQ==
    username: AgCcvNXcTNmlSvuq1kjlZmWI5xykT1VGWPxc3bXy2xujpV0Nuj6VR5+8HcVBmKuTFQKMgnp91wStwW6v7qcGwbIJ5Jd69q0R8noAv1ISP4csjebGhTrEoeoHJ2jOVqOI260mC5+8qp77Oy4/dBKGxcr9l7/SbO4YnQSghM9LKyOzAEtDyaURN4BDWNA/pTLuYBK+Zd2YJ59zxwRx84snsfbHRbstO4JkNiNoDy49CBzZp+R/QIV/I+XDZIUjp0yfDiWwKwE5aTLOLQV6at3ow+ac64947zI+jLbRlxNz+OIfw1Nua+GLSf2ACRaGwpLVrmnLk3VQkX4X9PZgTAo3r0xEmhAGR4OFK8vPnqP6s/VYhMgvvWKujfPpwS6YrsaGMDVxBFWkuxklsudcnOgFYGkKAjESKIt4hDMKsKIa56WPEw+Pt9VMCe/LJeeNS5row6nAsdDgMba3B8Nug7nDfiahhIOAuuu542kvE9hltuHfXkXROaGHF+0COcU1aIAd2FWb4DA8oEP/jlGBq8c2vfnkEVviggn7jkHsqlc8xYNQj+M0BtoH9kQAfNM2yd5dpJvPV0O/zzWFoSuJ/h7xVfDbIGfj2IS9JINS/6jOtxj952QwMW3B7LbObKU5XasBzkSAn26Pt64WfNs8eMSZhnx1o1iL3rnjElvDRCkvx8w7qOBubhDsA0s/oivRd6GaKTP/fngANsxZgzU=
  template:
    metadata:
      name: paperless-pg-creds
      namespace: apps
