---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: progist-pg-creds
  namespace: apps
spec:
  encryptedData:
    password: AgC0VVNV2ngTmVtRY4IdAZcOYsppu9zo3XWnFvJeR7r14+Ilvpk2qIAb1vAyJcx1DT+sFmjl553jJ6zwoMM5VgihZEyjAMo0oU64Cn6jqZxQxEqw02fpq6laiQ9krbhlg+fW5ny3gnJ11NQNCzuNVOLtDQfQarwyZzM8GEBlucCwdiID4iyliu+UFvdL9xGR0emetSowoRK0EDDHy1GisO9yNAgAXaCUg3z0yHfRIv69zL0LOKwPkcO3wZfWznnTxz+xgNlIEyMIBCodev9hKoAA9vsxNzT6E9hl3IFdsNqbYPXvyajIEGB0Q6P1CqClfiXCAmTIkFCSYavyHCCG/vdAYyJ7DJMuYagwiRUkMgEG8SD0G+buA5NUx2ZwxCGw4hi8FPMyo/w4YTtIsD1xiGKdTF+wCMfD5KjdFo8aiqr1IhFatu+G/qE+hH4eKIYUV5QsR71zL1WOkgx898YTcgiDOQL93glmgL6l4DPOR2TrTTQrUzX4p3csI63fJB1SG055vDVRZCqS8Fagll3DDpDj3E8it4t52byJeskijaL6KpX2sHRBt0tC8HlLHdvqKaUvht8A6S1gtLgeKZV2sdHaX7CUBi5glhdcDzrPdeaCCy+zKvSzAVu8ACy8NLxDLTUt6qT5hiaLSRcJrMC8hu2RoT/5jhCKLsmFukJhuBhY1+Z6RWC1g+g9jJh/5iEb4BfxFk/vIUIBzyU70LelRfb3aGMQk8bNXI+6VJ2kcMfjir3XX+grhrlqwHYM
    username: AgC/HgmylgbP+ZOS/LS8uRoiK/vep4tN7mBCxwAfEooP6oXuHOEnylG+JlohhxFF+mydPjTkVFj4hSKpQohsYrCiOiauV6WkM+vDJI2SBc657UESwSerfTEBH9oMgFOI+Yg9uniZ/dRtSju73z9DbPizP7jX4EPxcQeo455bJQiNwWheGlVbRoNtf8tYSbKGuvTkgAblNXr5aZpe5atY/4hHyM/gMjVi+gKanqc8ufUwCHEJ/l0CvR9cRyQ0c9WaMZvbngegod6niyV/82yIiaEdYJnkRaZGbpZ0O1kYGZUlaT/iv2w7qa7+mjCfKGZc0+8IeNcG9lgHQzZwGTFS9vBeMe9zsK2SbKLvoqdgOqeCrxUz+G60oPg9Inn4PZxWJxvn3przQ4tD9LAQLkLz9QtzcCgCEFfHRZ5a7stH0eXGS8ieHSDZU214psbrOzy/bgHzXs86l4Lt0P5XieEWxV5b+C6yAzRNGsVPM6LW02qwpvD9kgFs2KGmRrXqjLM/IV7zdpx8cQDReLHn12dK65nNfgmTsECUqeborU8BWAb+ybK0aiynb6nzFKStdBBAMUCcF4L/FIhhwAHuzJ78r+yCgB65p3plVwVqdm9EW9XWjg8KxsouB3mqqjj+vfvSIzC1jiGNvuuAz5yq9Z3tCiz7EUrlJfJZZ1eqvvM6Q4X3B8eIXP96UN+2AXj+Hj1dGSO52YaZvRhc
  template:
    metadata:
      name: progist-pg-creds
      namespace: apps
