---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: roundcube-pg-creds
  namespace: apps
spec:
  encryptedData:
    password: AgBuefs8UJTHNmQMp/1bKmU6VQKymCr0/B35HP24EvVzl5CbklLeFWfg553s/gMJfsAMpNhIm7aJsZYXfJFeMzZ50AjCnzF+RmmEubCDeMx63khPN6XCDxiUmTH213A4TJf43lmZNMFwUMEBcUva1D93ZEPNMhPt/JfF3/NpPoPW7gEBbKBq+ZWQYXRInk4orRNUXPZt9eAmhPpJajq0+XrpIGjzwRePtWJjwo4qEVd8oG3fMADwwXLiZ1/0sKZoIWeshUMrnO55lStjtV6ISwEDxldXAsbidiEJfvjWYOuru1TSfkJ4c8oRtoJsm+tt66OYkQo0kDXdHXt7bW0HFPzrqBtuNgsWF0eXqFdQmgFrTeg85fAxyNYLrAQSl74mSvhkHRiIkv/KAxH70VB6XTesgkMFLbkTXhk8skRFP03ugOy0SSY09o8LNOkrG0BdVTnCcXAqp6xjUZZAJ/u7uAsVWRfMZjVgGV7/0V/FGYw1FLs0snFZjbgjGqBLEPo8mq7gLu1fqrm56RaAQLeQh1mOUcWciCCrI3nmC/onYYhvf+3vDWITHaHlvpDTNc9dgOvid+0NdfrdWP7ad+HuOmriAtiPIoAt2BBYxeS5wlnTzPJ2hAO4ZCi+j2J3Vl7+xMjs7pJNoaTBI9YVYF7G2aCznXqQoEMSlrQmQ30McQllNsOvprhtFo+NIZ9AR6tbTyTKSueVnp2sVW5BST27X4NOBl2d1VMbE12C5nFL0SHabEuDE+f/ksKm1Ho=
    username: AgCuPEJ95zNWZpoykFO+EpfJcEano2QXS2km80spcH/EJORL3LF7KX5108ypgIu2U7cMrQ0higbbpWYxSNeZgJv1A60vuR7JjWZirzA1r8lKwcTbTVNXW/fZKzkpvQm46W39c34NK59CDvOAVLQaloVTSpfrqBvhnoWd30KlIGbZWIhW9yRrvgeUYR9uKhgpPOF1q2X3op+7vjwaQOA6b0H0Z5saljgopou5qpKkTFwiZRgTCfIjeNojmXQXC7PTov5PvOXoupp6Qra/T9GffZBAOZuanzebgWIL72z2phI/yoMVEFUstBWMK+x40ReQLqrxo5koKvCSMYMfaYiQOVNb37xpoCahnw9e7zfnlGY6C9jsmo5LllNJOxL7SluOoZZr2rDDPR4aG43UpsBdXq8X1UWhIskGGv21NvMdustixd3nfVy/bXrJmGmFmiq/uertWmeBuGkBVzLKsGJ9Asd1rfOP3/UzgxYikLqxGT20efyCzLTqLHNU2eehW8AT9IqvPnY1Fz42nkhGinXr69DuHdaXo7Tf+zlVZL3bWyueb/HM/YdqgTBtx5cjiupFfhw81RY6K3sseBIdDpiyT0lF7flGK0tGVh5kYMTFudlL5WG8TAYhR4NKVC6tnFIfZevvTgEdrmkYLOSByr7+PBxb9XLmKE1ubgEQpaBjALrCiWTLEJnJADYkRd9oim7h/v9AsnXOZVBUc7c=
  template:
    metadata:
      name: roundcube-pg-creds
      namespace: apps
