---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: stalwart-pg-creds
  namespace: apps
spec:
  encryptedData:
    password: AgCjuqwDRMf/4zq6+LhTTBZTo6XTLAoi+a+fMCpFDM/85ANL3gocTTs8OBb1BzKvlCnJ1EZgvKZFxDh6n+ccI1Q2n/cwohegU2Gh2wOkmbgqE3TU/7GSoeTPoMPWnY8gqb3RWIk703YxWcohhE/QU6tnCODts+lNHnPSIUpv7B2/xeEEH1VkW4DyERS7fWQ46l/iQH61MRHbPLB7ZFDhSlgRFfVNWkb2/+lt5uwCstex7VQyuW/1M1h4us1fFiTcR1CFdYkQjxHmxq74xquPR3vVuoEnK6hsGv0Hht70sXzutzgEYmpmhnIP3A04JIZxQ9psganV+N1wfqyyQt7Bt0SqLnY0y+BNePDC2SpTr7KXAKzb+RIpKu1dxCOxB7VMB+uSyhkKqdPrCBVtExzDfyuPtoPMsh/urVXJ9QdeTCH1hUaXrtoOE5WN7s3lNgVf2SCLXnSznFmMR9onHxECfEuHQ4twVpaRPUeG6uxAMxbU2N2TcLrEJn/8i31Gln39ZaBiDcs0y9flOYRgfmZ4hy6ZMEff+QOzLjSbzDYGog0dHCP/fPmqYDuZz43xth9at0UUob0w/UxJTilAr1gBSp2NuMFt74XzI3eMBUQwi6DFwrdFa9LbL90fjROzl5BZ5mxFb399Nl2S+sosBZzxGGVn5R9uBoavhE/enQijHAB1iOxcvrXa9U5aszfbvCWXFh+K2mYJJB3HqFsgVanrGI5IGeL7WDQuYEOIZMGpEhHtgQ==
    username: AgB4yANPTEHzHskDtAP/9T/PkIDvPCfMsVygBMA44xyU9ZIczcM6S08WuSP4BtzmyzGcocHIvCwfFE4JpxH936JaJZgHxJNeJklm9ff9+KXw5ED3c+lF5f9TFdcReWQuhzF5mSF7fVwfq1jOrGabwLgD7BVYrB0IZWNEL6CqGqKvXACNoby6swe9hiAFC+oDUPQU3XR32E1k8mSCooVXBYkPuPofDUB7XPyxmHjx7ReD/urflrfHVg1Efpa9VdtZETPrUiXZugqsDKSAa9sAZkUZaxB0tn8iobPj/CKIaSSQl0lHfWg1BXPGH2453aMmQX9BvnQZB5L2Cd8DKbzr7Si3UYP+gBN8mEEqrm3Y/9LWpVK2AYJme1vPOr4kSbMoZgtSot7d02E3V+dkU092i+CAG2eXhtVt9WJG4Kys0Lr/VnYiW/2jvmskYz1n2b424JgPDUB6IGytnyiBXOTtAIi0vc0t8gQLUvvRLPajJewz2ueSPu0vLle2TxvCwvDqWraw5sHFrectssj65Uv/SsIuryWK9r5Gl0OXRMtDhwLDK7hJDJasGSih66aabIuDpT/8aZ6gCz5lKgYthVLQxPQA7ixETZ7azKIP21VYDPiYiCwhVWOOrVVw1H5FlQTp1GEE8Uul8Vmjh28xwthUJ5R+P+Ng4cx1p1tP8fy1ghdST28RleA22KpZaSCJn5wVjf1Hnh9vcduajw==
  template:
    metadata:
      name: stalwart-pg-creds
      namespace: apps
    type: kubernetes.io/basic-auth
