---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: vaultwarden-pg-creds
  namespace: apps
spec:
  encryptedData:
    password: AgBP5qHe4dT/SHviEmPgYUM7FM63K6Y6cGGrLYD4nEZgUHjCz9A+TA3TGaIZjns6Rfqn/KbqGxppawKsRqjYOAQlpKURCSDQORQws1SW7H9JJ3l5y0vNcW9iaLgfrk/Mfapu0uP9iEvnR7+6+/Haj0VKjP1eq475HDU9UplTxvdsKNrE0LORH5oOYTc+LbuXvYeoqLCK4CTM3to0UPaYaIE2pXUwkl1G371t1g538/FWIJUskrl0w87lGVcV4f5iw29bzsdoDZ71BDJMhyAW2Oy3En8Rm1Be4OTUTlQLHnAXusVlVgBh3lsiWqG+98Nv5jEMobwOnbw2Flx+cqyqdGr56FWdJ+Ppz65nMzXiC2MLKneZdrgXl/HyjTjcnMEWLg5mDq/Y4T2HNinuQSEsyaOG15IV23DxCzq4Pe/zFIaDTsaO4cnRokAl/uu4/9+CFPV4wsian5MZLTZLnbGhVAu1cRyiqyNL/iZlQFkOTd/QX4eXQ6IxsEIYpP2rG0+QmcoRv068IhkI208XSF8tYNYt05pemvaBr3Nl47dzSRzJsGVoe6Ys8J94bWeiG5EV3oydiEj0PWKr4OPPJdlbJ4kzMM76KAm6aqm2cY/H4bmrQmGRBQq+1i/r/9M52UQPI88DSarA0zxAlHP/jFZ0AaZLdbZwN2RmoRJ5AChuyZHY3pjT/+2ArnB+mGHLoF+MHijoyLdeNWTcY0Gir8nRrjCds2CFJA9BIFbgpcJdwrnwiw==
    username: AgCr+a7VC4Ag/FGPWlVulSWy5hOb3mgBZUtM+/esrX+s512SIDmRN3S/B1196zsId/Mfu4Rq9YWpCPKvd0omfPudwxAAegPO4aAI5I881aGq36PaWClW92QFIhkvvXJSp5L9iI+GKnAWECE89/GRGSDx2OrBXzsmMxCYRyefKEgvof+JGWy5u7gflSXfXqeSgi37NFNYwi8uLaW1bb2XwyKi8VF3APeBMWUbCWgcOFMdSR+OXN/YMZla4I9Gnc1XheoRivVOEFKOFo4K9rWYS6dgJZOFl2kqk7+/DyabhRDCINY0WLJDMwBK6wW9ITcQ6bn4EwUqHJgou1LhyxQaYIz5oyzgCw6FMcVaKmWbmJY5naarh7+zRnKSt2GxDpvnGBqHD3GI4fbL/lX2YxtvFY6I65dF6ZlHPuh/Ot1ysKg5ZifM7kGjzlBR0hOzYcrPoqglsrTjj3KA1/kxmHKNnT+HyR5D2l/HDDEBpvIV2vev472X9QlZnJZELQOGRAIL+plZEvIiS1NLrTbuapDW2pWCl7KZHXIxjmta30Nhs+ZBM2PR3hag4zLBdkFiU6hWKuqnNCerOhOilb6/krsTLWvWnw/btMu5sb9s/myhZ6O8T2VbrZeVQGQFSIhnIG515IqyduuxxRkLQMziDjwyEnP9RnpfkMTXp6eN99w3CumGCsTHwV1SnOfv1ikTH6VKpRWyuqX02qC6yRFuhw==
  template:
    metadata:
      name: vaultwarden-pg-creds
      namespace: apps
    type: Opaque
