---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: vikunja-pg-creds
  namespace: apps
spec:
  encryptedData:
    password: AgA/q17zZU9R4GmaL9yqVhwPTdunWn3fAdmFjOBatSDtQZGXJMKIXGTc8AohBe6Iwmya73hGdKYAj/Z6SxprCAgpZ5IWj4dEs8T4J5JT5vHARfH/DwQvgYwAGZzbMeqKKLwirSQn4IiAGtrMAzKUYGQ9FbstzZoMeHVdpcRsKszjR/X0gf1i5v4oB+dAzYQkymGGhd9UfNYI/o/IZJotO8l6gihY6sXbwW6k8Ryy/O2hoXO/Xyvw+5JNlI5KS7eTqwr+yuZyqstfRZbAAkSgEGPTTHsfYFbzW4MTqRltpPpuz5vCiNUyxRGMSbUR9fTtg2mjWOP+OSuNq0u2va7L8Gnbz+uy03mxBaR8h61V1nFmmK3KGaY8VSaDYfJRh+FQ/9LdTYl3iwAQMzLMYna0Cb1dfrOe6zKNN8PPeE7+Lo/Xu5II0QOdgrD7/LMCJ6WgB1a9pBjmdSRYLpj4OSjx2fMyQISpPIkJfGNAq8XOvlaq6CCat/oJMlrOiu7rsjjCmdYqweWgSTLe6HPfVuYttl0/aFoDeYJQAtxilPVmwSjcaHOqZ73+klo2OAsfmMKv1qoChgkD9VfcuJLhUkGEL3KOQVV3qZ6fUU8RvMwPS7IcjCCyzdMLTga7b/mAWWND5DlpG3eP4tppN0NkQLlEqdbaBa4F2SgWuqEp2qSB6hTxAP8tzKFuaZR0y/aVtZUxe94XkMJlqsSlKSvD5W2eBSXqzcRPXfOZubldy6R0SA==
    username: AgAl6B7Oi9O6CqFtok0x8qI8IxZ6VOjhkuiVpQ0Ta495T+J2ZuCAsp7TSMxSSv5qGBQmboljbAAmoZEr7GrJLV91/WKOCURWZKorXgQFkwmYxO6msM+j79rCcr2skLJ0t8tklEIrw1nTLptQfaSSxRSma09pVLLJBQjWNvoFKLTGNQQtg1pIBWGADJq9M6tmEmwYCA9S0PEnQLZYZKm2mel1uA/woLCiKQg1Glr1zO26A6MGQBMHGkl74/JZkl3GOkd113Phn4VvSXyulkpEB4BiTuVpw2PVQiIREgaQ0xanZXyBbEbJ6Phdhx2tEKB5vNh9BOwoZiUxdGzmKhnyW/bAvBz0CR0ja78P0xz55SasGmUm60ICg3uZQzqiiJcJwYGN+ccQRH9nVeprTXR6EKEgIz8rv6Z4JD6P13zwj6sKuqwBneYK1PF1wxzvlgpGNit5HuYq/wzpi7HAZQJHdjpQh2QABioYHgrNW2HvWV7HBP2AwbdE+TPqsuJGcPojoAV3H5EThI0JVOdWPb7E4IvH2B48MHqDnSPaPqvJKgvBLDLHIkkTem4pyR217WHZ6/XGMOfcNU/3PmYCg/aBZcO8cxnuztsGryN0ac88ivteIKif7EoWJp2O/nynmfz0eqXXDgPrOybGDxx/Dmyl8mS+3TTr/hCdkag7w9te88S5/YPSf5p9Lva1+bRMdrkd9J6TX9YR9ZKq
  template:
    metadata:
      name: vikunja-pg-creds
      namespace: apps
    type: Opaque
