---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: trek-secrets
  namespace: apps
spec:
  encryptedData:
    ENCRYPTION_KEY: AgB2V8bMyEA8QHXOkLZQ+F8ziBG+CO3U331MP1cvGWKgMWGxyHEoIhnC9spTVxahCAw3GTPU8312ItlD4VjQdoXuBhUfYRUQwi7B1bx8RcPPRdWHXMQP4+tYnA8+zrXrKrSjS4CpGRKGP3bO1asy13CFb1P0PYslVC7q0/TVcfqx9IB/DJd6AZf7N4ZZeVae+ofHhsexVc+2kbybUlgFTc/e8tTrA9aQ1iU25koWeZ3IeAExCgJn3T5Z2w7s+ygGJ3zn17ZNUqSDGL05325vhOodZ5Z3/sbjaeQgoqXDuos+ePXmw9uX03LvjkXPVoszc2pC6zldm6dCu6FoFETh/nOSvG5A4qrc+Ej7CdzW52fTyGe77kXXC2z34cC8bRD9r1d9XZz6iZVATyMfWrAW9024Z3FdJbbm78QYTR2hlgM6pR5+tlXnTceGAJib0icYTagGJqfA5MsnBNHbiJWsX2zKE+vGx0OUS5zTciS1DhWhOMRKylRdgrBX9sZR1XIfFn2XsKFvRqEQC953HOONIrGokLwyOSAoht7u677W2mJOS8l4Hbl6EjheJKdnl1Zergyld4sOxJXTvoRopo0jO4gBR6BOOGlwrAmJ8mBhywkdhNyMxeO54eZtIKAVKU8A27qu62Ot1kzXodExYiLg/r9vjTvVogRaOg18nBmmwqYNYKapGMofZ+AswDvwOAOmhLPdqWHB2Bv7vwWEj3GgsHBzxcwCyH3lAxF3GUFGm/FAo0mJ5BE0/BQAptzGM5ERlexTuETWXsQwAm9uX7p1prul
  template:
    metadata:
      name: trek-secrets
      namespace: apps
    type: Opaque
