---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: databasus-minio-secrets
  namespace: infra
spec:
  encryptedData:
    access-key: AgCQmLAZAbe54OL9Vt74wj0HmAfDSAae0M6GbXtt/Ynlo6zjJeOvZVhBU8I5h1JC2lZnb/Y002sjooFm4jPlL3TYCjbVtrwyHT3FU22cgVBNwSwt8odaQKm0yW0Z3et9nuRwCPaGbP7Y4g+4VUmPboq0eueh41waWTXHhQfv+Jo8uTlmxBpjy5lw4C9hRMYatorgMqrqLX2RQgwSfk9DFXXscvnu8fbi/YAD304COvQsmImsdHW69E8oXcGOu9Qn3QM/PFBhhk0CvjLQxUaOAxQGkSq9rTqaKdym6hKayZEDv95k/ZxbLpYGTwmcG/snl0kTHJXXPyd3bQ94ojw8JDSI5MJ+rgqVGHyjYtYei/6sHQnrUFk4U1ZI7saCl+Iah1M+Ds6pY6E6m5nPxhMOxAbaXBMNPaC+bTDRy8/begwCpeyhcYR++5BOfrj6sAOrlqW+Bh+ukf/KQsi9tKbL2B9JxPD/uVn812HbUWZ0qoO8z7He3KEjTK/FUsVCYsrquZMbW5OEmLNFPik+fEDKqv4r/uZAfSqSriAP1Q6+r6+WNbAnMCKhWuDjWee5XVuwCsAII5QUZU2dSCeYYfrFL2OcpUC49sWHzzoRt45+40gmTvzLAiyGGgayXW12rVaogKYCp2l0YAdAIhGkPTFpt+r3q0o8LQ3cftr2Ig8+JNMO8Igy9EplFgqgNIeeueJQ7CjQtYvLL7NGsFAdXYfQ8w==
    secret-key: AgBv/BOfGv0QVojOq9dLk1lBuXklTIm4feCtwuME7YK4aUrxaKfgqkRSWo32vre22uVE3uLCyehJHvDcvI16rmwTkxxTg7o5aBJvu/K/Dxtq4VFXkXFq0M6rbeSdZbE+dxRwRRYx3lKKCYyzBkNmJ4U58IofpH1hGBDLRHfgm/C7LeNMtlgkrkuVep0dP/XYSsu8AXk9m/AyFQDy6Rq9wLRx/1zndmzg6RBIEagWUkcWvr+fuW8WLx8XHAqipKrvUEi+sq77VFpdCM1DwuB1Z2BnpSOrIuwWUE/c45FkvjSYgOamZ7ITk3XnIadwkEp81Ft3xDLDht1Qs3zv8G4EUPqJHkm6cM1OuDy7aDJVWZmx7jOqXTVQyVW+/Gj40Yu2RAlXaIyawMCK6Q2pwYIWJH4qye2v1VrvbAvWcJasalWXPJLEfPiSNb7unspSG7td7M65c8Vq5dzWT33IrGxX3NDGmqh540WJd8b3X+W1zHtyD7W+tOH7/saqWBtODHmSwzy3eJ5CJkB4FcCLo3UhjvnDA3Iu8butC9Nrc+KujOA1Lu7fZdm6h+AWTKGMgLHduqTfcQvvmZ12aocUto77X3EEEkgPg1nK1das4acVTDRmINOs0w+sH5aUA6UftHZOFsVC/+vO/cCXzuqIfKEMftshs8DmmK7Fe6FUfsYVTKKF7hig79bFbLLJ3F7x8ABhpZZW1zj+CkHTO+EyBFzcparWs6eak5WEzzhQKt91zMYBtA==
  template:
    metadata:
      name: databasus-minio-secrets
      namespace: infra
    type: Opaque
